* <2021-03-12 Fri>

Introductions

what we'll do. Combination of improv and roleplaying, I think it can be super usefu.

We will practice improv exercises, learn some improv principles, and our goal is to practice improvise scenes.
We'll start simple with ordinary characters, then try to set them in a fant

Are you comfortable with video?


Pretzel, Sebastian, 21, Mexico, wants to get better at roleplaying.
threefrognight, beth. clinical lab, teach at a college.
necromas, johnas, 19. serving in US army. firearms, writing.
imsocold, tyler, 17, writing, dnd, few groups.


pen
book
story
relationships
trainwreck
death
taxes
buerocracy
government

can't wait to go swimming.


fantasy

pirate

* <2021-03-12 Fri>


Barwick Leo - started playing dnd, loved it, wants to get better.
Mia - larping, wants to learn more
pom, played a lot of dnd, wants to be good at roleplaying and improvising
Oliver - new, wants to get better.
Samwise - lotr/starwars fan. new to dnd.  watched for awhile. loves fantastical stories.
loves rpgs, witcher. stage acting, voice acting.

more fictional

ill try to run more of those, schedule is hectic
announce, just message me
story games



add a detail

tripping balls

talking horse i appreciate when people like my mane



* <2021-03-13 Sat>
Ilde

Badger - GMing. For 5E. deaf kids. loves playing.
Clyde - making up on the spot. from writer's room. does 
cyber - new gm. freelance writer.
cian - just wanted to try.

suggestion
5 things about the environment


eviction notice from global warning



discord timer.
5-6 is the ideal number.

purple pineapple pilferer

3 minute scenes.


Two goals:
1. Getting people to the point of being able to write a funny sketch. without gimmicky exercises
2. Helping players to skill up at roleplay.
What do you need for that?

Improv/Storytelling principle, Roleplay application (why it matters), Exercise.
(Once they understand, we JUST play these games. And I walk them through the curriculum when we'll need to introduce new people/)
First person initiates the scene, they play it with the 2nd person, then the 2nd person initiates the next scene and plays it with the 3rd person, and so on.

dont need separate improv and roleplaying applications.

2-player scenes, rotate, take turns in discord voice chat.
You follow, then you initiate. Non-players provide suggestions (and comments if the exercise needs them)

Take ideas from word associations as suggestions.
Get non-playing people to make one-word suggestions!

Players can’t ever agree on what to do next, or GM shuts down people ideas. But it’s not just about agreeing, it’s about embracing people’s ideas and building on top of that, creating a story together.

Details. Who we are, where does the story take place.



One exercise I do with improv groups is to set a timer for ten minutes, and challenge them to do 5 scenes. Then 10 scenes. Then 20 scenes.
Another good game for practicing getting a sense of what's important in a scene is "Half Life". Do a scene. Then repeat the same scene, but twice as fast. Then twice as fast again.
And then there's just getting people comfortable with calling edits. RPG groups aren't used to that. While I'd expect the GM to take most of the responsibility for pacing the game, everyone should be willing to call an end to a scene. So just doing scenes and having people say "and scene" when they think it's done will help make everybody more comfortable with doing it (and having it done to their scene).

* <2021-03-14 Sun>
Cory - ??
Silmara - roleplaying since 11,
Dawn - roleplaying for a long time, recently started DMing DND.
Red - not the best at improv,
Oliver - dnd player and a gm. good at it.
Talia.




* <2021-06-08 Tue>
Children.
Quire Karate.
Warming up local cords.
Catholic priests.
Will we have an antagonist who will be a catholic priest we have to defeat.
shotgun cheatcode at the end.
pulled out my bazooka.

rap intros.
suggestion.

my name is lumen and i'm here to say.
pencil to the mustard mustard to the pencil.
east west north south
street
coming up after me will be
dj unicorn sprinkles
wakka wakk
sprinkle unicorn.

Beast

east side
dola bills
i bought elephant

cup of brass

Santa

feet socks pajamas rama

Slick
Scary

gator soup gator sandwitch

dj futurama

im from alabama, my sister, my siter is my mister

tax collector
dj slam dunk

tax collector.

try to rhyme this time

my tragic past


steve - 1
chaco - 2
prompt tells you what to do.

spy
vampire

im falling in love with you
sir, please dont fire me.
if you can beat me in the game of operation, we can go on a date.

programmed prompts.
we've recently played pitchstorm and it was really fun.
and it'll something like this would be a good 
i think
give me a line, write it in the chat.
we dont need prompts for it, pepole can just improvise that.
everyone gives a character and a plot

pitch around the twist episode
something happens and it's weirdly cursed.
weird magic curse.
acronym

used condom
key to your moms chest
character
butler who's aspiring to be more. daddy sugar.
gardener bomond nickson
covering up a murder

something they have to do

chris - butler
and gardener
being a head butler has its' privileges.
finding out what happened a day ago.

president
queen of england
sherlock

caveman

in soviet russia we offend accent.

regular global assault
recangular gastrointestinal
advertisements
replacing gun alarm
relapsing
gigantic
regularly growing apples.
really gigantic armadillo
rare gigantic armadillo

electric boogaloo
punched the guy through the window

mr zanzibar

debra
armadaddy
>> write down props

