* Phase Big Dig
Queen Cyntia she/them
Lobster

I trust you - this is your first mistake.
ooh yeah daddy.

hired as a group to make a delivery.
Grizzbert - dude.


Open Desert.
Here to deliver a package.
Stylized american south west.
Lonesome crab. Americans version of 
wide as he is tall and just as thick. as a piece of chiece.

Resupply small mining town called harmony.

Taters 
mocksy and your spunky attitude
The debts must be paid.
your skills have grown 10 fold.

main trade
arcs off from the mesa.
smashed.

any of them hot.

all the wagons were facing in the opposite direction away from us.
they were all trying to leave.

vagon parts, broken crates, makeshift barricade.
horn in the distance.

disguise myself as a dwarf.

time for us to make haste
galloping towards 

summersault backflip
jebediah
so brave so majestic
erputs from the earth, giant open maw.

I think we were severely underpaid for this mission.
50g.
resupply, and return the ore.
dynamite.

Humbug Von Bluff
burning chunks of worm raining down.

so much for the water we were supposed to supply here.

stupendous

40 foot sinkhole, purple worm, gigantic worm. 
100s of feet long.

mama ate all the dragons

where do you reckon these worms came from.
foreman/mayor.
mithral trade.
sweet liquid. juice of the agave.
custom made of mithril.
motherload, deep mithral vein.
under harmony there's underdark. 
draw use our tunnels to come up to the surface.
mine collapse, sinkhole open.
honest mistake.
fancy shamans who controls purple worms.
brilliant diplmats, kidnap him
bearers of bigass bomb
super bomb.
sleeps at night.
get her and the drow.

torture just a scouth

roadrunners

foolhardy
Bob Bill Boom
Great songs will be sung about your great sacrifice.

sand runner.
dune buggy.

ball of mithral.

memorize some drow coprses appearances.

Speech
Can I give them my best independence day speech.

this is the first day of the rest of your lives.
Boom

once again my plans have been ruined by a group of middling kids.

little tear drops 
ah yes the beauty of capitalism.
i enjoy it and marvel at it.

who here is the bravest, who wants to be first at the elevator of doom.
so we proceed to our inevitable fate

crystals are magically generated.
elf-liek footprints.
light systems.
faint purple glow
grizzbert my friend fancy a fancy crystal
alarm
patrol

ship has kinda sailed.
pulls out a bunch of popcorn, shares it with taters.
slink into 

horrifying creature that drows would fear.
giant centipedes.
that was amazing.
running towards us, not back to his buddies.

tenderly embraces him.

cheeze fondue waffles.
he was beautiful singer.

upstage
killed the whole village.

delicious with mustard
moondancing pricks, im drow, 

take us to your leader.
worm guy.
no crying over burnt fungus.

Pasputin
darkspire
Hans and 
Spans

our plan.
we arrive at a shaman.
we have a bomb to plant.
diplomacy.

boils us alive in our own skin.
Greg Jason and May

okay, we're not killing him, hes' on our side.
massive stalagmite.
mesa built into it.
boney baloney
Jason

crazy cat lady.
mithral

all we had to do is to 911 a city of drow.

incorpora
* <2021-06-03 Thu> Dinosaur adventure
Freeform Roleplay. A group of friendly people who love storytelling and improvisation go on imaginary adventures.

You were going about your daily business...
[Describe your character, and what they're just normally doing.]
You feel a strange sensation in your stomach, all the colors drain from the world around you, then everything explodes in colors you've never seen. You see the objects and people around you blend into each other, you hear chanting filled with desperate, primal energy. You begin to dissolve, your body becomes one with the air around you, and the universe itself. Everything is darkness, not even that, just an absolute kack of existence,
You can hear each other thoughts.
You are ripped out of the comforting nothingness, you feel your bodies begin to undissolve, reassemble, and find yourself standing in the middle of a cave. The fire burning inside it is blinding, but once your eyes adjust, you see the cave is filled with people. Women, children, old people. Everyone looks dirty and scared. Women are tending to injured and bleeding warriors.
In front of you you see an extremely old woman. She is holding an ivory staff with a small fighrine of a mammoth at its very top. Shaman looks at you and her face fills with hope. 
[old lady voice] The saviors! The chosen ones!
- Cave battle. Muzzled dinosaur riders, some of them are literally dinosaurs holding spears in their claws. Morph/unmorph?
- Warriors run away. Slit their throat in a bad roll. 
- T-Rex. Shaman sacrifices herself, gives them the staff as a symbol of her power.
- Crossing the river of lava. Sabertooth carnivore kangaroos are jumping over it! Haha, capture one.
- A herd of dinosaurs, they capture one.
- Apes are jumping off of the tree tops, surround you, capture you.
- In the middle of the tree arena. Apes on trees. You and captured fangs are in the middle.
- Escape, vampire caves, vampire conversion ritual. Monkeys hair falls off
- Valley slowly being [engulfed] by the lake of lava. A well guarded tent on the opposite side (eerily similar to what you have seen when you arrived, women, children, tending to burn victims), [capture/befriend anwarrior to find] a dinosaur graveyard.
//Using staff would turn you into a carnivore mammoth. Killing a mammoth is the most heinous crime, sacrilege.
//Tusk tribe - a series of caves in the mountains, mammoths here and there.

Gethro Stoneleaf, little cabin, nanny yaga, helping her out. talking to serpents, snake whisperer.
Nathaniel Voluris - badass, slices things.

if thats' you must call us.

raptor warrior.

describe
describe how you defeat him.

dinosaur begins to sway its' head and its hips like a charmed snake.

looks at you confused, licks your face.

describe how you cast the spell, what does it do, how do you feel.

Scaly

stop big boom boom
Grog

Smashes it's head.
17-18
rog is angry

I'd rather die than abandon my family.

not a true natural disaster.
OF COURSE. Shaman caused it to justify his dinosaur thing!
defeat the shaman.

nuzzles your neck.

in celebration bam, kills another prisoner.

ape don't like people,
need another approach, try something else.
challenge alpha.

you want to challenge me?

signal for scaly.
3 with advantage.

new alpha.

speak what you wish to speak to us.

present, gift of our tribe to yours.

rock of peace, rock of friendship.

dancing around the fire
reward.
redhead caveman.
* Interview
How do I make this show better, what do you want me to talk about?

Adventure Brainstorming

just adapt
rule free

modular

one shot adventures
campaigns
* <2021-06-10 Thu> Into The Deep
ryan reynolds

# @Gomer (Jeremiah Stoneleaf)
Jeremiah Stonelaef. Nana Yaga. Human.
Familiar - small snake.
# @Phaselancer (Frojurn Vinterfest)
Dragonborn wizard. On a quest to find ikea furniture. Wizard. Very tall.
# @ScottishComedian (Mycke Pancake)
Redeem his family. Half-elf wizard.
# Stacy (Andre)
Andre. Blacksmith, trying to make money. Elven artificer.
Uses armor as prosthetics.

Describe your characters.
* <2021-06-22 Tue> Do or Dry
Lotter the Otter
I have been doing russian like this
eat your radish
pills that make me a nightmare for people like you

Gentle
frolick

Plain ottor, hardwood armor, eyepatch, plant fiber, halbert
mr voul

why order pizza in the beginning if she didn't have the money to pay for it
mage hand

watership down

Necklace love your mom.
glass coke bottles
one water bottle

mush santiago, onto our next adventure.

Santiago
Dirty Monty
Sinister foreshadowing

too dehydrated

resolve centuries of racial tension.
elizabeth the beaver

My darling lives in Cyntia.

Theodosia Chipmunk
dictate therm
i hate to watch him go but I love to watch him leave.

some cannons
horn to communicate.

#jok "
Im gonna have wet nightmares about this



import { compare, hash } from 'bcryptjs'
import { sign } from 'jsonwebtoken'
const { APP_SECRET } = process.env

* <2021-06-22 Tue>
>> Im not asking for intellectual property, I'm asking to let me open source this under creative commons. That way I get all the rights 100%, and so does everyone.
And it's squeaky clean. And there's no danger since this is a separate project.
Which *I* can later use as I please.

you must release creative commons:
https://creativecommons.org/licenses/by-sa/3.0/us/
