
* LFG Post

[Online] [Other] Looking for 2-3 people who want to improvise an adventure together.

Hi! I'm looking for 2-3 people who want to meet in the discord voice chat, and improvise a one-shot adventure together. I've run brainstorming sessions like this before, and they work really well - it's fun to make up stories with a group of friendly and creative people,  stretch your creative muscles, bounce ideas off each other, and if you're a GM - it's a great way to create adventures you can run for your players.

If you've never made an adventure before - don't worry, you'll get a hang of it really quickly, it's about as easy as playing a regular RPG. We will take a [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/), go through it step by step, and fill it with our ideas. Then we pick our favorite ones, and try to combine them together into a story that makes sense. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.

If this sounds like fun - send me a message!


[Online] [Other] Looking for 2-3 people who want to brainstorm an adventure together.

Hi! Recently I have been running brainstorming sessions where 3-4 people meet in the discord voice chat, and we improvise a one-shot adventure together. It's super fun to stretch your creative muscles by making up stories with a bunch of friendly people, and if you're a GM - it's a great way to create adventures you can run for your players.

We improvise stories by using the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/). We go through it step by step, answer the questions, and fill it with our ideas. Then we pick our favorite ones, and try to combine them together into a story that makes sense. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.

If you've never made an adventure before - don't worry, you'll get a hang of it really quickly, it's about as easy as playing a regular RPG. There's no pressure to be a brilliant writer or improviser, you can just join a session, listen in, and when you have some ideas - add them to the story we're making.

If this sounds like fun - send me a message!



Hi! Recently I have been running brainstorming sessions where 3-4 people meet in the discord voice chat, and we improvise a one-shot adventure together. It's super fun to stretch your creative muscles by making up stories with a bunch of friendly people, and if you're a GM - it's a great way to create adventures you can run for your players.

We improvise stories by using the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/). We go through it step by step, answer the questions, and fill it with our ideas. Then we pick our favorite ones, and try to combine them together into a story that makes sense. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.

If you've never made an adventure before - don't worry, you'll get a hang of it really quickly, it's about as easy as playing a regular RPG. There's no pressure to be a brilliant writer or improviser, you can just join a session, listen in, and when you have some ideas - add them to the story we're making.

If this sounds like fun - send me a message!



Hi! Recently I have been running brainstorming sessions where 3-4 people meet in the discord voice chat, and we improvise a one-shot adventure together. It's super fun to make up stories and stretch your creative muscles, and if you're a GM - this is a great way to create adventures you can run for your players.

We create adventures by using the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/). We go through it step by step, answer the questions, fill it with our ideas. Then we pick our favorite ones, and try to combine them together into a story that makes sense. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.

If you've never made an adventure before - don't worry, you'll get a hang of it really quickly, it's about as easy as playing a regular RPG, there's no pressure to be a brilliant writer or improviser.

If making up lighthearted stories with a bunch of friendly people sounds like fun - send me a message!




[Online] [Other] Looking for 2-3 people who want to brainstorm an adventure together.

Hi! Recently I have been running brainstorming sessions where 3-4 people meet in the discord voice chat, and we improvise a one-shot adventure. It's super fun to make up stories together, to stretch your creative muscles, and if you're a GM - this is a great way to create adventures you can run for your players.

We create adventures by using the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/) that contains a list of questions that guide us through the brainstorming process. We go through the process of creating an adventure step by step, fill the template with our ideas, pick our favorite ones, and try to combine them together into a story that makes sense. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.

If that sounds interesting - send me a message!

(If you've never made an adventure before - don't worry, I'll walk you through the basics and you'll get a hang of it really quickly. It's pretty chill and lighthearted, there's no pressure to be a brilliant writer or improviser. If you just want to listen in and contribute an idea or two when you come up with something cool - that's totally fine.)





* LFG Communities Pitch
**Adventure Writer's Room - GMs Brainstorming Adventures Together**

We are a group of GMs who meet in the discord voice chat, and challenge ourselves to improvise a one-shot adventure in 2 hours. Our goal is to brainstorm fun ideas and improvise stories together in a chill, lighthearted, no-pressure environment. It's super fun, it works, and it really helps with creating adventures! Usually, by the end of the brainstorming session, we have a solid outline of an adventure we can run for our players.

Here's how it works:

- We organize a brainstorming session, meet in the discord voice chat, and challenge ourselves to improvise a one-shot adventure in 2 hours.
- We create adventures by filling in the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/) together. This template contains a list of questions that will guide us through the brainstorming process. We copy the template into a new google doc editable by everyone in the group, and fill it with our ideas.
- We go through the process of creating an adventure step by step, one part of adventure at a time - idea, antagonist, setting, challenges, etc. For every step, we make a list of ideas. We briefly discuss them, and pick our favorite ones.
- Then we try to combine these ideas together into a story that makes sense. After a while the process becomes less structured and more freeform - we’re trying to fill in the gaps, enhance the ideas we have, find answers to the remaining questions, and turn it all into a complete outline of an adventure. To get a better sense of how this works, watch Brandon Sanderson doing [something similar](https://www.youtube.com/playlist?list=PLTT-Xb7kSZWWH_LW5aDRhc5FMJNZgyeAd) in his fantasy writing class.
- At the end of the session we have a draft/outline of an awesome adventure that gives us all the information we need to run it for our players, or playtest it between ourselves.
- Sometimes after the session we can use the [Adventure Template](https://docs.google.com/document/d/15s0bm3G3AnOVxayBSZ8X1RbazSWdB-HXPSFTTCQVWxY/) to summarize our ideas, clean up our draft, make our adventure easy to prep and run. You can see the list of adventures we have created [here](https://rpgadventures.io/).

**We’re looking for some friendly and creative people to join us!**

If you want to improvise some stories with us - come join our [discord server](https://discord.gg/UVNxeQE)!

If you've never made an adventure before - that's ok, don't be shy, join one of our brainstorms, and you'll see that creating an adventure can actually be pretty easy and fun. There are no prerequisites, no expectations about being a brilliant GM, writer or improviser. If you’re friendly and are interested in stretching your creative muscles - you’re welcome to join! If you're not a GM but a player, and making up stories sounds fun - come join us as well!

* Writer's Room
** Session Announcement
Hey, @everyone! Who's up for a brainstorming session at 9AM CST (1.5 hours from now)?

I'm looking for 2-4 people. If you can join us - leave a message in this chat.
We'll try to make a short, lighthearted, low-combat, system-agnostic, fantasy one-shot adventure.
It usually takes around 2 hours, give or take.

** Pre-session post
@everyone We begin in 10 minutes and we have some spots open. If you're free - come join us!

This is the google doc we'll be filling in with ideas, open it before we begin:
https://docs.google.com/document/d/1Vgd4MJkk-WVwRXmmnbgHd518CWa05Ka59NSq_hems-I/
In the google doc go to Tools > Preferences, and uncheck "Automatically Detect Lists", otherwise google docs autoformatting will be really annoying.
Feel free to start filling in the first section with the ideas before we begin the session.

If you haven't read the guidelines yet - check them out:
https://docs.google.com/document/d/17wZ5GA_JcbgxrEXRejA4sYSRqFHp0hE7o56rIHWEXPM/

I also recommend to open a note-taking app, can be convenient. And you can open the writing prompts generator (https://playmirage.io/prompts), if you feel like it'll be useful to you.


* LFG
** Zoom Game Announcement
[Online] [Other] A novice GM looking for some friendly people to join my actual play one-shot (zoom video chat uploaded to youtube, very simple, no special requirements for equipment or skill, all you need is a webcam)

Hi everyone! Novice GM here. I have recently started experimenting with recording my games and uploading them to youtube - so we aren't just playing, but also creating something cool. I'm looking for some nice people who want to participate in this little project.

There are no specific requirements for your improv skill or equipment, all you need is a webcam. We're not trying to be the Critical Role or Dimension 20, it is just a simple low-production-value low-expectations experiment. We'll roll the dice in the discord text chat, talk over zoom video chat, and after the game I'll edit the video a bit and upload it to youtube (if it turns out well). If you haven't used zoom yet - it's super easy to set up, about 5 minutes. You can take a look at one of our previous games [here](https://youtube.com/watch?v=Cn9vV_wHpY4).

Novice players are welcome! We'll start simple, and get better as we go along. I'm hoping to find some friendly people who are interested in learning and growing together. If you want to experiment with this sort of thing, learn how it's done, and can be patient if things go wrong - you're welcome to join the game!

The system we'll be playing is called [Mirage](https://playmirage.io) - a lighthearted, low-combat, rules-light, storytelling/improv-focused roleplaying game. It's like DnD, but focused on social/creative aspects, without all the math, intricate rules, and the slow combat encounters. 

It's very simple, it takes 10-20 minutes to understand the rules and prepare for the game, it'll be perfect for a youtube show. All you need to start playing is the basic understanding of the [rules](https://playmirage.io/rules), and a [character sheet](https://playmirage.io/character-sheet) (you can use a premade one, or I can help you make a new one). If you're unfamiliar with the system - don't worry, I'll help you out, just let me know if you have any questions or need any help with the rules or character creation.

I need 3 players, we'll play a short and simple lighthearted one-shot, should be about 2-3 hours long. We'll start playing in about 2-3 hours, once the players are ready.

If that sounds interesting - send me a message(`lumen#7925` on Discord).

** Mirage Game Announcement  
[Online][Other] Novice GM looking for 2-4 friendly people to help me playtest my new adventure. Lighthearted/Spooky RP-focused one-shot, over voice chat, today, at 8 AM GMT.

Hi! I'm a novice GM, I have made a new one-shot adventure, and I'm looking for 2-4 friendly people to help me playtest it.

We'll be playing [Mirage](https://playmirage.io) - a lighthearted, low-combat, rules-light, storytelling/improv-focused roleplaying game. It's like DnD, but focused on social/creative aspects, without all the math, intricate rules, and the slow combat encounters.

It takes 10-20 minites to prepare for the game. All you need to start playing is the basic understanding of the [rules](https://playmirage.io/rules), and a character sheet (you can use a premade one, or I can help you make a new one).

If that sounds interesting - send me a message(`lumen#7925` on Discord).

Novice players are welcome!



* Discord
** Mirage Gme annoucnement  
**Novice GM looking for some friendly people to help me playtest my new adventure. **
**Type**:  One-Shot, about 2-hours long. Lighthearted, roleplay-focused, low-combat, theatre-of-the-mind (with illustrations and dice rolls in the discord channel).
**Time:** Ideally within the next few hours (Once we get 3-4 players.) 

We'll be playing Mirage - a lighthearted, low-combat, rules-light, storytelling/improv-focused roleplaying game. It's like DnD, but focused on social/creative aspects, without all the math, intricate rules, and the slow combat encounters.

It takes 10-20 minites to prepare for the game. All you need to start playing is the basic understanding of the rules (https://playmirage.io/rules), and a character sheet (you can use a premade one, or I can help you make a new one).

If that sounds interesting - send me a message. Once we have enough players, we'll decide when it's convenient for everyone to start playing.

Novice players are welcome!







**Novice GM looking for some friendly people to help me playtest my new adventure. **
**Type**:  One-Shot, about 2-hours long. Lighthearted, roleplay-focused, low-combat, theatre-of-the-mind (with illustrations and dice rolls in the discord channel).
**Time:** Ideally within the next few hours (Once we get 3-4 players.) 

We'll be playing Mirage - a lighthearted, low-combat, rules-light, storytelling/improv-focused roleplaying game. It's like DnD, but focused on social/creative aspects, without all the math, intricate rules, and the slow combat encounters.

It takes 10-20 minites to prepare for the game. All you need to start playing is the basic understanding of the rules (https://playmirage.io/rules), and a character sheet (you can use a premade one, or I can help you make a new one).

If that sounds interesting - send me a message. Once we have enough players, we'll decide when it's convenient for everyone to start playing.

Novice players are welcome!



**Novice GM looking for some friendly people to help me playtest my new adventure. **
**Type**:  One-Shot, about 2-hours long. Lighthearted, roleplay-focused, low-combat, theatre-of-the-mind (with illustrations and dice rolls in the discord channel).
**Time:** Ideally within the next few hours (Once we get 3-4 players.) 

We'll be playing Mirage - a lighthearted, low-combat, rules-light, storytelling/improv-focused roleplaying game. It's like DnD, but focused on social/creative aspects, without all the math, intricate rules, and the slow combat encounters.

It takes 10-20 minites to prepare for the game. All you need to start playing is the basic understanding of the rules (https://playmirage.io/rules), and a character sheet (you can use a premade one, or I can help you make a new one).

If that sounds interesting - send me a message. Once we have enough players, we'll decide when it's convenient for everyone to start playing.

Novice players are welcome!




@everyone We begin in 10 minutes and we have some spots open. If you're free - come join us!

We'll try to make a short, lighthearted, low-combat, system-agnostic, fantasy one-shot adventure taking place in the Academy of Arcane Arts and Adventures (basically Hogwarts, but it’s a college, and it's for every kind of adventurer, not just wizards).

This is the google doc we'll be filling in with ideas, open it before we begin:
https://docs.google.com/document/d/1ylg9MkMR-fFNLB7xw5Et5s0fJpqb57fOUEWR5CeYiHc/
In the google doc go to Tools > Preferences, and uncheck "Automatically Detect Lists", otherwise google docs autoformatting will be really annoying. 
Feel free to start filling in the first section with the ideas before we begin the session.

If you haven't read the guidelines yet - check them out:
https://docs.google.com/document/d/17wZ5GA_JcbgxrEXRejA4sYSRqFHp0hE7o56rIHWEXPM/

I also recommend to open a note-taking app, can be convenient. And you can open the writing prompts generator (https://playmirage.io/prompts), if you feel like it'll be useful to you.
