# LFG reddit
[Online][Other] Looking for 2-4 friendly people who like improvisation and freeform roleplay. We start in 2 hours (if I'll find enough players).

Hey, everyone! I'm looking for people who, like me, love the social/creative aspects of games like DnD, but not the intricate rules and long combat encounters.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the (extremely short and simple) [rules](https://rpgadventures.io/story-games) to learn how to play, and send me a message! I'm `lumen#7925` on Discord.

(I have never done this before, so it will be a bit of an experiment, but I think this can be super fun if it works! )

# LFG reddit 2
[Online][Other] Looking for 2-4 friendly people who like improvisation and freeform roleplay and want to play a lighthearted one-shot adventure. We start in 2 hours (if I'll find enough players).

Hi! I'm looking looking for some friendly people who like improvisation and freeform roleplay, want to play a very rules-light, collaboratively improvised one-shot adventure, and are willing to experiment with a new game format. Think of it as a combination of roleplaying, brainstorming, collaborative storytelling, and improv.

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how to play, make your character, and send me a message! I'm `lumen#7925` on Discord.

//

Together we'll improvise a story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story.

# LFG reddit 3
[Online][Other] Looking for 2-3 friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format. We start in 1.5 hours (5PM GMT).

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how to play, make your character, and send me a message! I'm `lumen#7925` on Discord.

* Discord
# LFG server 1
**Looking for 1-2 more players for our game, we start in an hour**

**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Availability:** 2
**Time:** An hour from now (if I can find enough players)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, and are willing to experiment with a new game format.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# LFG server 2
**Looking for 1-2 more players for our game, we start in 1 hour (5PM GMT)**

**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Availability:** 2
**Time:** 1 hour from now (5PM GMT)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Fairy's forest
@Available Players 
**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Players:** Looking for 1-2 more people
**Time:** One hour from now (5PM GMT)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Discord and Dragons
Platform: Discord Voice Chat, Freeform Roleplay
Looking for 1-2 more players for our lighthearted improv/roleplay-focused game. 
We start in an hour (5PM GMT).

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# RPG talk
**Improvised Lighthearted One-Shot**
**System:** Freeform Roleplay. Story Games (https://rpgadventures.io/story-games).
**Platform:** Discord Voice Chat
**Time:** Today, 5PM GMT (1 hour from now).
**Players:** Looking for 1-2 more people.
**Format:**  One shot. 
**Tone:** Casual, lighthearted, improvised.
**Requirements:** 18 or older. Both novice and experienced people are welcome.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Digital dungeons academy
@Looking for Group 
__**Game System:**__ Freeform Story Games (https://rpgadventures.io/story-games)
__**Platform:**__ Discord Voice Chat
__**When:**__ 7PM GMT (1 hour from now)
__**Frequency:**__ Today
__**Format:**__ Lighthearted improvised one shot.
__**Openings:**__ 2
__**Experience Required:**__ Both novice and experienced people are welcome.
__**Synopsis:**__
Hey, everyone! I'm looking for 1-2 friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format. 

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!


# old

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, and are willing to experiment with a new game format.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!
* LFG/improv Community post

**Story Games**

Story games are for people who love improvisation and freeform roleplay. We go on imaginary one-shot adventures in a lighthearted atmosphere with other friendly and creative people. It is a combination of roleplaying, brainstorming, collaborative storytelling, and improv.

Together we improvise stories from scratch, with no preparation. We create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story and resolve it in an awesome and satisfying climax.

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how this works, make your character, and [join](https://discord.gg/gNrJJNMuyD) our Discord to play with us.
* Discord Reply
Hi! Thanks for messaging me! Yep, you're welcome to join us!
Come join the server where we're playing: https://discord.gg/gNrJJNMuyD
Take a look at the rules https://rpgadventures.io/story-games, make your character, and post them in #characters.
Let me know if you have any questions or need any help with this stuff!

# Already played
Hi! Thanks for messaging me!
[We've already played the game I've announced, but we'll be playing more games soon.]

Come join the server where we're playing: https://discord.gg/gNrJJNMuyD
And keep an eye on #game-announcements, I'll be posting notifications about the upcoming games there.
Also take a look at the rules https://rpgadventures.io/story-games, and make your character.

* Adbox

Story games are for people who love improvisation and freeform roleplay. It is a combination of roleplaying, brainstorming, collaborative storytelling, and improv. Together we go on imaginary adventures, improvise stories from scratch, with no preparation. We take turns GMing scenes for each other, play as our characters, and make things up as we go along.

collaborative storytelling,



Story games are for people who love improvisation and freeform roleplay. Together we go on imaginary adventures improvised from scratch, with no preparation. Come play with us!

We are a group of GMs who meet in the discord voice chat, and challenge ourselves to improvise a one-shot adventure in 2 hours. Our goal is to have fun brainstorming ideas in a chill, lighthearted, no-pressure environment. We’re looking for some friendly and creative people to join us! "

 - set up the scenes and roleplay through them,
roleplay through the story, 

We use the [Story Games Template](https://docs.google.com/document/d/1Eg6jXg47vivpyKBfPQnO_SKSV0BIO1RMurGhRSc1rDA/) to guide us through the game.  We use [prompts](https://rpgadventures.io/prompts) to establish the important details about our adventure: our goal, adventure setting, and the important characters. We roleplay through the story as we go, taking turns GMing scenes for each other.





We're looking for some friendly people who love improvisation and freeform roleplay, want to play rules-light, collaboratively improvised adventures, and are willing to experiment with a new game format.

We're looking for some friendly and creative people who want to go on lighthearted collaboratively improvised adventures, and are willing to experiment with a new game format.


Together we improvise an adventure from scratch, with no preparation, guided by the [story template](https://docs.google.com/document/d/1Eg6jXg47vivpyKBfPQnO_SKSV0BIO1RMurGhRSc1rDA/) and [prompts](https://rpgadventures.io/prompts). We roleplay through it as we go, taking turns GMing scenes for each other.


**Story Games**
We're looking for people who want to play very rules-light, collaboratively improvised adventures, and are willing to experiment with a new game format.

Story games are for people who love improvisation and roleplaying. We go on imaginary one-shot adventures in a lighthearted atmosphere with other friendly and creative people. It is a combination of freeform roleplay, brainstorming, collaborative storytelling, and improv. 

Together we improvise an adventure from scratch, with no preparation, guided by the story template and prompts. We roleplay through it as we go, taking turns GMing scenes for each other.

We are looking for people who love improvisation and roleplay.



