* <2021-02-21 Sun>


Imprisoned on the ship.
Survive the person who's hunting us down.

prisoners of evil overlord.

sky dragon monster
Air kraken

Job situation.

meg man - goblin
Amanda - elise. helped with armor repairs. kaylee from firefly.
brown hair and pig tails.

there's an armory with all our stuff.

Charky - cat person.


Orc guards.

Careful not to interrupt.

Fancy elves.
Roguish criminals.

make sure not to interrupt and ask people if they wanted to speak up.
just say that when

3 classes of orc kindergarden.

they took all our stuff.

he's one eyed, he can't really wink.

you're pretty smart for a mortal.

elfs - turn things around.

you can definitely do it.

i would roll my eeys if I had any eyes.

grappling hook
smoke poitons.

come with me if you want to live



thext challenge?x

sneak between people.
he knows magic.

crawl on the outside of the

how do you attack the captain

turns into a puddle of goo.

steer the wheel
steer the people off the ship.

* <2021-05-26 Wed> Pitchstorm

Gomer (Charles) - 3-4 years GMing. thomas?
Michelle - playing for 5 years, high school level, roleplaying.
Necro - studying linguistics, half a year.
Oliver - 1 year, jack of all trades.
Red - likes roleplaying, UK college.


innocent veterinarian - forced to fight

# Ves Phone Home
small town veterinarian, investigating farm, abducted by gray aliens,
fight in a coliseum against the chaotic and evil unicorns.
they don't got humans in teh pits.

# Maeloki - 1
# Warman
Marine escape the asylum
modern postapoc ww2
doesn't like his job, nuclear explosions.
he's bored.
musical acts - add piano that eats people.

# Michelle
# Unfortunate clingon
alien heiress ambassador laid of as heiress and get started as an architect.
trying to prove herself, diplomatic
watch with grandfather.
went on a camping trip

# Necro - Mouth needed shut
mad scientist - malevolent sockpuppets
superfiber, made sentient socks, with AI.
stolen from dimension filled with fish.

# Oliver - Take me to your leader.
innocent framed fraud - alien warlord dominate earthj
john johnson, average everyday man, happy family, get away with stealing,
decides to pin it on him.
warlord says we must go, take us to your leader.
in this dream is johns neighbor

# Red - Future samurai and tv aliens
time traveling samurai in the future, connects satellite tv to alien dimension.
accepts teh challenge to fight alien warriors.
in love with ninja turtle.

# Woofles - Wrong Address
alien princess learning about human world - survive the apocalypse
traveling accross the galaxy on her tour, musician.

riends on last night befroe leaving for college - tries to save their classmates from a superhero on a class trip.

# Gabble gabble toil in trouble

worst cannibal - body snatching aliens
thanks killing the revenge of the turkeys

caveman - drug dealer
time is money, we're in hollywood new york
teens love memes

have to picture it

do a huge line of coke
ugh, this one will do


talking ape - defend his enemy from a farmhouse
ahtes animals, grandpa brought monkey

# Apetown USA - in belgium


announce your own games

moi tai boxing skill

Boneman of the Salmon

Benedict Cumberbatch
Zoe Deshanel
Quirky comedy.

lovable school shooter, genie in a lamp

mean girls sequel

robin williams

if i can't have my m16 and my bible in another, then what's the point.

join a cult

Midsommar meets Shindlers List

wears octopus as a hat as his symbol of power.

More Legs More Probelms.

Benedict Cumberbatch

Pokesaurus

riding a raptor
acquired
dip my head into the coke bucket.
