
* Reddit CTA
---
**Story Games**

This adventure was made by the [Story Games](https://discord.gg/gNrJJNMuyD) community. We have improvised this story from scratch, during our game. 

We are a group of players who love improvisation and freeform roleplay. We create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, trying to make up a fun story as we go. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - learn more about our games [here](https://rpgadventures.io/story-games), and come [play with us](https://discord.gg/gNrJJNMuyD)!

---

**Story Games**

We are a group of people who love improvisation and freeform roleplay. We improvised this adventure from scratch, during our game. We create our characters, decide what adventure we want to go on, do a bit of brainstorming to establish the important details about our adventure, and then take turns GMing scenes for each other, trying to make up a fun story as we go. Think of it as a combination of freeform roleplay, brainstorming, and improv.

We're looking for some friendly and creative people to join us!

Learn more [here](https://rpgadventures.io/story-games), and come [play with us](https://discord.gg/gNrJJNMuyD)!

---

**Story Games**

We are a group of people who love improvisation and freeform roleplay. We improvised this adventure from scratch, during our game. We create our characters, decide what adventure we want to go on, do a bit of brainstorming to establish the important details about our adventure, and then take turns GMing scenes for each other, trying to make up a fun story as we go. Think of it as a combination of freeform roleplay, brainstorming, and improv.

**We're looking for some friendly and creative people to join us!**

Learn more [here](https://rpgadventures.io/story-games), and come [play with us](https://discord.gg/gNrJJNMuyD)!


---

**Story Games**

We are a group of people who love improvisation and freeform roleplay. We improvised this adventure from scratch, during our game. We create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. **We're looking for friendly and creative people to join us!**

Learn more [here](https://rpgadventures.io/story-games), and come [play with us](https://discord.gg/gNrJJNMuyD)!


 A group of players improvise an adventure from scratch, with no preparation, guided by the story template and prompts. We freeform-roleplay through it as we go, taking turns GMing scenes for each other.

We improvise our adventures from scratch, with no preparation, and take turns GMing scenes for each other. 


We improvise adventures from scratch, with no preparation, and roleplay through them as we go, taking turns GMing scenes for each other.

We improvise adventures without preparation, and freeform-roleplay through them as we go, taking turns GMing scenes for each other.

Don't explain how it works, just benefits, fun, cta. Dont need to explain collab GMing, just invite people to join. this is the output, the benefit

We are a group of people who love improvisation and freeform roleplay. We improvised this adventure from scratch, with no preparation. We're looking for friendly and creative people to join us! Learn more, and come play with us!
 Each participant picks a scene or two to write, and adds them to the Adventure Template.We are a group of people who love improvisation and freeform roleplay. We improvised this adventure from scratch, during our game. We're looking for friendly and creative people to join us! Learn more, and come play with us!

* Forever GMs
[Online][Other] Looking for "Forever GMs" who enjoy improvisation/roleplay, want to play as a PC for a change, and also get better at improvised GMing. We'll play a lighthearted freeform one-shot where we take turns GMing scenes for each other. I need 2-3 people.

This is an experimental game, but I've played it a few times before, and it's been really fun. Together we will improvise a story from scratch, without doing any of the prep work in advance. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other. Think of it as a combination of freeform roleplay, brainstorming, and improv.

It's a great way for us to finally play as PCs, practice running improvised games, get better at storytelling, learn from the other GMs, and make up stories we can later run for our players.

If that sounds interesting - come [learn how to play](https://rpgadventures.io/story-games) (the rules are very short and simple), make your character, and send me a message! I'm `lumen#7925` on Discord.

We can run a game in a couple of hours if I find enough people, or we'll organize one later today, depending on when everyone is available.

** 



[Online][Other] Looking for "Forever GMs" who enjoy improvisation/roleplay, want to play as a PC for a change, and also get better at improvised GMing. We'll play a lighthearted freeform one-shot where we take turns GMing scenes for each other. I need 2-3 people.

Together we will try to improvise a fun story from scratch, without doing any of the prep work in advance. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other.

That way we all get to be players, get better at running improvised games, and make up stories we can later run for our players. This is an experimental game, but I've played it a few times before and it's been really fun.

If that sounds interesting - come [learn how to play](https://rpgadventures.io/story-games) (the rules are very short and simple), make your character, and send me a message! I'm `lumen#7925` on Discord.

We can run a game in a couple of hours if I find enough people, or we'll organize one later today, depending on when everyone is available.


[Online][Other] Looking for "Forever GMs" who enjoy improvisation/roleplay and would like to play a lighthearted freeform one-shot where we take turns GMing scenes for each other. I need 2-3 people.

Hi! I want to find a few fellow GMs who would like to play as a PC for a change and also get better at improvised GMing. We will take turns

Together we will improvise our story from scratch, without doing any of the prep work in advance. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other. We will make things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

That way we all get to be players, get better at running improvised scenes, make up stories you can later run for your players, and practice GMing them at the same time.


If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how to play, make your character, and send me a message! I'm `lumen#7925` on Discord.


* r/LFG
# LFG reddit 3
[Online][Other] Looking for 2-3 friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format. We start in 1.5 hours (5PM GMT).

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how to play, make your character, and send me a message! I'm `lumen#7925` on Discord.

# LFG reddit
[Online][Other] Looking for 2-4 friendly people who like improvisation and freeform roleplay. We start in 2 hours (if I'll find enough players).

Hey, everyone! I'm looking for people who, like me, love the social/creative aspects of games like DnD, but not the intricate rules and long combat encounters.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the (extremely short and simple) [rules](https://rpgadventures.io/story-games) to learn how to play, and send me a message! I'm `lumen#7925` on Discord.

(I have never done this before, so it will be a bit of an experiment, but I think this can be super fun if it works! )

# LFG reddit 2
[Online][Other] Looking for 2-4 friendly people who like improvisation and freeform roleplay and want to play a lighthearted one-shot adventure. We start in 2 hours (if I'll find enough players).

Hi! I'm looking looking for some friendly people who like improvisation and freeform roleplay, want to play a very rules-light, collaboratively improvised one-shot adventure, and are willing to experiment with a new game format. Think of it as a combination of roleplaying, brainstorming, collaborative storytelling, and improv.

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how to play, make your character, and send me a message! I'm `lumen#7925` on Discord.

//

Together we'll improvise a story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story.


* Discord
**Improvised Lighthearted One-Shot**
**System:** Freeform Roleplay. Story Games (https://rpgadventures.io/story-games).
**Platform:** Discord Voice Chat
**Time:** Today, 5PM GMT (1 hour from now).
**Players:** Looking for 1-2 more people.
**Format:**  One shot. 
**Tone:** Casual, lighthearted, improvised.
**Requirements:** 18 or older. Both novice and experienced people are welcome.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!


# LFG server 1
**Looking for 1-2 more players for our game, we start in an hour**

**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Availability:** 2
**Time:** An hour from now (if I can find enough players)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, and are willing to experiment with a new game format.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# LFG server 2
**Looking for 1-2 more players for our game, we start in 1 hour (5PM GMT)**

**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Availability:** 2
**Time:** 1 hour from now (5PM GMT)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Fairy's forest
@Available Players 
**System:** Freeform Roleplay
**Platform:** Discord Voice Chat
**Players:** Looking for 1-2 more people
**Time:** One hour from now (5PM GMT)
**Tone:** Casual, lighthearted.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Discord and Dragons
Platform: Discord Voice Chat, Freeform Roleplay
Looking for 1-2 more players for our lighthearted improv/roleplay-focused game. 
We start in an hour (5PM GMT).

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# RPG talk
**Improvised Lighthearted One-Shot**
**System:** Freeform Roleplay. Story Games (https://rpgadventures.io/story-games).
**Platform:** Discord Voice Chat
**Time:** Today, 5PM GMT (1 hour from now).
**Players:** Looking for 1-2 more people.
**Format:**  One shot. 
**Tone:** Casual, lighthearted, improvised.
**Requirements:** 18 or older. Both novice and experienced people are welcome.

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format.

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!

# Digital dungeons academy
@Looking for Group 
__**Game System:**__ Freeform Story Games (https://rpgadventures.io/story-games)
__**Platform:**__ Discord Voice Chat
__**When:**__ 7PM GMT (1 hour from now)
__**Frequency:**__ Today
__**Format:**__ Lighthearted improvised one shot.
__**Openings:**__ 2
__**Experience Required:**__ Both novice and experienced people are welcome.
__**Synopsis:**__
Hey, everyone! I'm looking for 1-2 friendly people who like improvisation and freeform roleplay, want to go on a lighthearted one-shot adventure, and are willing to experiment with a new game format. 

Together we will improvise our story from scratch, with no preparation. We'll create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story. Think of it as a combination of freeform roleplay, brainstorming, and improv. 

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!


# old

Hey, everyone! I'm looking for some friendly people who like improvisation and freeform roleplay, and are willing to experiment with a new game format.

I want to play very rules-light, collaboratively improvised adventures. Think of it as a combination of freeform roleplay, brainstorming, and improv.

If that sounds like fun - come read the rules (https://rpgadventures.io/story-games) to learn how to play, and send me a message!
* LFG/improv Weekly Community post
** Improv
**Story Games**

Story games are for people who love improvisation and freeform roleplay. We go on imaginary adventures in a lighthearted atmosphere with other friendly and creative people. It is a combination of roleplaying, improv, brainstorming, and collaborative storytelling.

Together we improvise stories from scratch, with no preparation. We create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, making things up as we go along, trying to tell a fun story and resolve it in an awesome and satisfying climax.

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how this works, make your character, and [join](https://discord.gg/gNrJJNMuyD) our Discord to play with us.

** LFG
**Story Games**

Story games are for people who love improvisation and freeform roleplay. We go on imaginary one-shot adventures in a lighthearted atmosphere with other friendly and creative people. It is a combination of roleplaying, brainstorming, collaborative storytelling, and improv.

Together we improvise stories from scratch, with no preparation. We create our characters, decide what adventure we want to go on, and then take turns GMing scenes for each other, trying to make up a fun story as we go.

We're looking for some friendly and creative people to join us!

If that sounds like fun - come take a look at the very short and simple [rules](https://rpgadventures.io/story-games) to learn how this works, make your character, and [join](https://discord.gg/gNrJJNMuyD) our Discord to play with us.

* Discord Reply
Hi! Thanks for messaging me! Yep, you're welcome to join us!
Come join the server where we're playing: https://discord.gg/gNrJJNMuyD
Take a look at the rules https://rpgadventures.io/story-games, make your character, and post them in #characters.
Let me know if you have any questions or need any help with this stuff!

# Already played
Hi! Thanks for messaging me!
[We've already played the game I've announced, but we'll be playing more games soon.]

Come join the server where we're playing: https://discord.gg/gNrJJNMuyD
And keep an eye on #game-announcements, I'll be posting notifications about the upcoming games there.
Also take a look at the rules https://rpgadventures.io/story-games, and make your character.

* Adbox

Story games are for people who love improvisation and freeform roleplay. It is a combination of roleplaying, brainstorming, collaborative storytelling, and improv. Together we go on imaginary adventures, improvise stories from scratch, with no preparation. We take turns GMing scenes for each other, play as our characters, and make things up as we go along.

collaborative storytelling,



Story games are for people who love improvisation and freeform roleplay. Together we go on imaginary adventures improvised from scratch, with no preparation. Come play with us!

We are a group of GMs who meet in the discord voice chat, and challenge ourselves to improvise a one-shot adventure in 2 hours. Our goal is to have fun brainstorming ideas in a chill, lighthearted, no-pressure environment. We’re looking for some friendly and creative people to join us! "

 - set up the scenes and roleplay through them,
roleplay through the story, 

We use the [Story Games Template](https://docs.google.com/document/d/1Eg6jXg47vivpyKBfPQnO_SKSV0BIO1RMurGhRSc1rDA/) to guide us through the game.  We use [prompts](https://rpgadventures.io/prompts) to establish the important details about our adventure: our goal, adventure setting, and the important characters. We roleplay through the story as we go, taking turns GMing scenes for each other.





We're looking for some friendly people who love improvisation and freeform roleplay, want to play rules-light, collaboratively improvised adventures, and are willing to experiment with a new game format.

We're looking for some friendly and creative people who want to go on lighthearted collaboratively improvised adventures, and are willing to experiment with a new game format.


Together we improvise an adventure from scratch, with no preparation, guided by the [story template](https://docs.google.com/document/d/1Eg6jXg47vivpyKBfPQnO_SKSV0BIO1RMurGhRSc1rDA/) and [prompts](https://rpgadventures.io/prompts). We roleplay through it as we go, taking turns GMing scenes for each other.


**Story Games**
We're looking for people who want to play very rules-light, collaboratively improvised adventures, and are willing to experiment with a new game format.

Story games are for people who love improvisation and roleplaying. We go on imaginary one-shot adventures in a lighthearted atmosphere with other friendly and creative people. It is a combination of freeform roleplay, brainstorming, collaborative storytelling, and improv. 

Together we improvise an adventure from scratch, with no preparation, guided by the story template and prompts. We roleplay through it as we go, taking turns GMing scenes for each other.

We are looking for people who love improvisation and roleplay.



We're looking for some friendly and creative people to join us!

Pick something you want from them that’s important to you but which they are unwilling to give you.

Should relationship just be a part of roleplaying guideliens?
Yes. It's not essential to the game, it's just a part of being good at it.

What makes the problem difficult and why must we solve it? What's at stake, what happens if we fail?



Exciting Adventure Hook
The first scene that draws our heroes into action, gives them the first set of tasks to accomplish. 
How do the heroes encounter the problem? Drama? Mystery? Danger? What's at stake, what happens if they fail?
 
The First Steps
First obstacle the heroes need to overcome as they strive towards their goal. First milestone they need to reach.

Surprising Midpoint
Unexpected complication that changes the direction of the story, raises the stakes and threat level. 
Twist/reveal that redefines the goal? Antagonist makes a move? Crisis when everything goes wrong?

Awesome Climax
The final, epic, most important/dangerous challenge that resolves the main conflict. Exciting ending. Cool set piece.

Resolution
Outcomes/consequences of the adventure. How does the world (and heroes’ lives) change after the climax?



Adventure Hook and Climax to the most experienced players.

https://drive.google.com/file/d/10A8oreEaFIXgY-KHvwl07xcytwzuVApQ/

Drama? Mystery? Danger? In medias res?


Surprising Midpoint
Important Milestone. Twist/reveal changes the direction of the story, redefines the goal, raises stakes / threat level.

Crisis
Everything goes wrong, the goal becomes much harder to achieve. Unexpected complication? Major setback? Antagonist makes a move? 



Exciting Adventure Hook
How do we encounter the problem? Draws our heroes into action, gives us the first set of tasks to accomplish. 
 
The First Steps
First obstacle the heroes need to overcome as they strive towards their goal. First milestone they need to reach.

Surprising Midpoint, Major Milestone
Difficult challenge? Unexpected complication changes the direction of the story, raises the stakes and threat level? 
Twist/reveal redefines the goal? Major setback? Crisis, everything goes wrong? Antagonist makes a move? 

Awesome Climax
The final, epic, most important/dangerous challenge that resolves the main conflict. Exciting ending. Cool setpiece.

Resolution
Outcomes/consequences of the adventure. How does the world (and heroes’ lives) change after the climax?




Surprising Midpoint
Unexpected twist/reveal changes the direction of the story, redefines the goal, raises the stakes and threat level.
Complication, setback? Crisis, everything goes wrong? Antagonist makes a move? 
the goal becomes much harder to achieve. 
Major Milestone.  



Surprising Midpoint
Unexpected twist/reveal changes the direction of the story, redefines the goal, raises the stakes and threat level.
Complication, setback? Crisis, everything goes wrong? Antagonist makes a move? 
the goal becomes much harder to achieve. 
Major Milestone.  
Everything goes wrong, the goal becomes much harder to achieve.  More difficult challenge? 



Exciting Adventure Hook
How do we encounter the problem? Draws our heroes into action, gives us the first set of tasks to accomplish. 
 
The First Steps
First obstacle the heroes need to overcome as they strive towards their goal.

Surprising Midpoint
Important Milestone. Unexpected complication changes the direction of the story? Twist/reveal redefines the goal? 

A More Difficult Challenge
Second, more difficult challenge. Raise the stakes and threat level.

Crisis
Everything goes wrong, major setback, the goal becomes much harder to achieve. Antagonist makes their move?

Awesome Climax
The final, epic, most important/dangerous challenge that resolves the main conflict. Exciting ending. Cool setpiece.

Resolution
Outcomes/consequences of the adventure. How does the world (and heroes’ lives) change after the climax?



Goal
Go on a mission to…
Solve a problem with (or caused by)...
Help someone else to...
Prevent the antagonist from…

Action:
Obtain/Steal/Kidnap/Capture.
Save/Rescue/Protect/Defend.
Escort/Deliver/Smuggle.
Kill/Destroy/Invade.
Find/Reach/Chase.
Escape/Survive.
Infiltrate/spy on.
Investigate. Solve mystery.
Negotiate with or about. 
Explore.

Target: 
Person, Group, Creature, Item, Location, Info.





Antagonist
Evil ruler and his minions. 
Outlaws. Criminals. Pirates.
Organized crime. Mafia, crime families.
Spies. Special agents.
Secret Society/Conspiracy/Cult.
Mad Scientist/Wizard.


Corrupt government. Oppressive regime.
Swarm/Horde/Tribe/Army.
Monsters/Creatures.


Ah, right. If you start with a setting, you can't have really specific antagonists.
I mean antagonists are specific. You can't have both a list of antagonists and settings.

* <2021-02-28 Sun>
Holy shit! Is this what these "high concept" things are?
Technologies/Magics?
If you take settings, and that, and antagonists - that about covers 90% of HCs?
AND those can be mixed in and out.
And I can make SO MANY of those.
Look at a list of HC movies, and RaM episodes.
See if 99% of them aren't one of those things.

Inside the Game, VR, Holodeck.

A young police officer must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph.

twist, something unexpected.

Change one of the elements to something unexpected.
What's different about them?

Okay, going through movies/episodes, breaking them down.
Setting, fictional element, goal, antagonist.

Alien planet. Defend a location. Mind-control avatar.
Pirates. Ancient curse. Get an item.
Toy Story: Sentient objects. Return home from hazardous environment?
Monsters Inc: World of monsters. Take person to a place while being stealthy.
Harry Potter: Magic school. Defeat dark lord. All the spells.

Gravity falls.
Sentient statues. Solve a murder mystery.
Anti-gravity amulet.
Ghosts. Survive/escape location.
Shrinking. Escape. Stop villain from stealing a thing.

die hard is JUST defend a location from terrorists. why is this such high concept?

Combine multilpe goals, those are your challenges.
Combine a series of 3 goals.
 String 3 goals together, achieve one in order to achieve the other.


Adventure brainstorming/writing process, templates, and prompts.

Abilities,

You can't establish relationship in advance tho.
and you can't do "what do you want from this quest?"
which IS pretty great, let's face it.

Even if characters are premade. Establishing a goal and a relationship is COOL.

 Is there history between your characters? What do you think of each other?

Create tension you want to have between your characters.
It should be something both players are happy with and interested in exploring even if the characters hate it.

It should probably just be a guideline.
YES. Goals (stuff you want from this quest) and relationships - that's just a part of good roleplaying. doesn't need to be encoded in teh rules.


Yes... So these wouldn't be the rules, these would be improv skills.


```
**Name**: <Character's Name>
**Description**: <Appearance, personality, occupation, motivations, goals.>
**Abilities**: <Cool powers, special skills, useful items.>
```

<!-- Then we improvise the scenes of our story.  -->



Protagonists (Player Characters)
Description: Who are you? Name, appearance, personality, occupation, goals. 
Abilities: What can you do? Cool powers, special skills, useful items in your inventory. 
Relationship: Establish a connection to another PC. Conflict, what do you want from them that they won’t give you?


Story Games - a free, simple, GMless system for people who love improvisation, collaborative storytelling, and freeform roleplay. Designed to help you to improvise adventures from scratch, with no preparation. 

Hi everyone! I've made quite a lot of progress on my game since my last post, I'd love it if you could take a look at it and let me know what you think!

The [rules](https://rpgadventures.io/story-games) are very short, simple, and easy to explain to the new people. It takes 5-10 minutes to read them and begin playing. There are just enough rules to help you improvise and tell stories, but no intricate "crunchy" mechanics that distract you from roleplaying.

The main purpose of the game is to help players to improvise one-shot adventures from scratch, with no preparation. It is a combination of freeform roleplay a long-form improv game. You don't need a GM or a premade adventure to play it, just a group of 3-5 creative people who enjoy storytelling.

The game is meant to provide structure to brainstorming and improv, making them more accessible to everyone, although some roleplaying/storytelling/GMing experience is recommended.

This game is also excellent for GMs. Playing it is a great way to get better at improvised GMing, create adventures you can later run for your players, and to enjoy playing through the story as a PC. [Here's](https://rpgadventures.io/adventure/great-beyond/) an example of an adventure we have improvised during one of our games.

If this sounds like fun - come [join](https://discord.gg/gNrJJNMuyD) our Discord to play with us!

This game is mainly inspired by the game "Follow" by Ben Robbins (it is actually compatible with the quests from that book). And Fiasco.



It can be played as a lighthearted casual party game, or a long-term campaign .




7-8 AM US Eastern Standard Time.
Plenty of people are happy to use reddit as a distraction at work, but will not let it take up their free time.
The best time would be Monday, as people tend to procrastinate when they know they got lots of work ahead of them.
As a rule of thumb, early in the work day (8-10 AM ET) is usually the best. 
The best time to post on Monday is between 6 A.M. and 8 A.M.
On Sundays, Reddit people prefer to sleep a bit longer, logging in to Reddit only after 8 A.M. and staying there until noon. 


>> Conflict between plot, setting, characters. What does my character want, why can't they have it? Because it's a core game loop, solving problems, overcoming obstacles.
What do they want, what do they need, what's preventing them from realizing the difference between those two things?
Combining things in an interesting way that creates conflict.
>> Good writers just spend A LOT more time coming up with things and combining them in different ways.


Relationship: Establish a connection to another PC. Conflict, what do you want from them that they won’t give you?



Prompt about pace.
Start scenes as close to the action as possible, end them as soon as action is over.

The Six Truths are six true things about the campaign that mark it as different from other game worlds.
First, they tell you how this game world is different from others.

### Keep up good pace
Aim for a 3-hour game. 40 minutes for brainstorm, 30 minutes per plot point (adventure hook and resolution can be shorter, climax can be longer). Keep scenes short. Start scenes as close to the action as possible, end them as soon as the interesting part over.

Summarize things if necessary.

Each player makes one scene per plot point?

Rename scenes to plot points?
Something active to do with them.



Every scene should advance the story,
 If you’ve shown some decision being made or revealed something about a character or the situation, that’s a good scene. 

YES. Say that those are plot points, and define what to actively do with them, other than just looking and using them as a guide.
Just aim to hit them as we play.

The template contains a list of key plot points.
which we strive to hit?
which we use to guide our improv.


NICE. Good enough.
Nice. Perfect. Just "strive to incorporate them into our story, use them to guide our improv."

Perfect, what more do you need.



"",

"",

Combine goals. Main goal requires 2-3 subgoals
</p>



Cool stuff you can do. Cool powers, special skills, useful items.






<p className="smaller"></p>

flavor for locations? Meh.
1 Captured
2 Abandoned
3 Advanced
4 Monolithic
5 Endangered
6 Treacherous
1 Protected
2 Volatile
3 Beautiful
4 Deceptive
5 Shattered
6 Savage
1 Exotic
2 Fragile
3 Civilized
4 Hidden
5 Active
6 Moving

It WOULD be nice to have a list of challenges that aren't just goals.
Although let's face it, that's what they are.
1 Danger (imperil)
2 Obstacle (slow)
3 Barrier (prevent)
4 Passage (advance)
5 Resource (enable)
6 Refuge (refresh)

1 Desert
2 Jungle
3 Oceanic
4 Frozen
5 Volcanic
6 Junkyard
1 Artificial
2 Hollow
3 Sentient
4 Metropolis
5 Paradisiac
6 Dark
1 Shattered
2 Gaseous
3 Mountain
4 Swamp
5 Tropical


