* session-announcement
Hey, @everyone! Who’s free to brainstorm an adventure two hours from now, at 4PM BST?

We’ll try to make a short, lighthearted, low-combat, system-agnostic adventure set in a fantasy world, a story that anyone can run as a one-shot, or drop into their campaign as a side quest.

We'll use the brainstorming template (https://rpgadventures.io/brainstorming-template) to guide us through the adventure creation process. We'll go through it step by step, and fill it with our ideas. 

1. First, we will brainstorm ideas and establish the key elements of our adventure: interesting premise, the goal our players will pursue, setting and locations they'll visit, NPCs they'll meet, challenges they'll encounter.

2. Then, we will try to to combine these ideas into a short outline of an adventure, put it all together into a list of scenes that add up to an interesting story that makes sense.

3. Finally, if we have enough time left, we will turn this outline into a one-page adventure. We'll use the adventure template (https://rpgadventures.io/adventure-template) to create a short summary of everything we have brainstormed, which we (or other people) can use to run the adventure for the players.

We will aim for a 2-3 hour session, about 1 hour for each step of the process.
I’m looking for 3-4 people. If you can join us - leave a message in this chat.
If you have some time before the section - take a look at our brainstorming guidelines (http://rpgadventures.io/brainstorming-guidelines).
* /r/lfg invite
# [Online][Other] Looking for 2-3 friendly and creative people who want to brainstorm a one-shot adventure together. We'll meet in the voice chat and try to create a story that we can later run for our players. We start 2 hours from now, at 4PM BST.
Hi! I'm looking for 2-3 people who want to brainstorm some story ideas and create an adventure together. We'll meet in the discord voice chat, and try to improvise a one-shot adventure in 2-3 hours. It's really fun to bounce ideas off of other people, stretch your creative muscles, and if we're successful - we'll end up making a story we can run for our players.

You don't need to have any experience with creating adventures, you're welcome to join even if you've never GMd before - don't worry, you'll get a hang of it really quickly, this is a great way to learn and try to create your first adventure.

If I find enough people who want to participate, we'll start 2 hours from now (at 4PM BST).

If that sounds interesting - send me a message, I'm `lumen#7925` on discord.

---

### How it Works

We’ll try to make a short, lighthearted, low-combat, system-agnostic adventure set in a fantasy world, a story that anyone can drop into their campaign as a quest, or run as a one-shot.

We'll use the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/) to guide us through the adventure creation process. We'll go through it step by step, and fill it with our ideas. 

1. First, we will brainstorm ideas and establish the key elements of our adventure: interesting premise, the goal our players will pursue, setting and locations they'll visit, NPCs they'll meet, challenges they'll encounter.

2. Then, we'll try to to combine these ideas into a short outline of an adventure, put it all together into a list of scenes that add up to an interesting story that makes sense.

3. Finally, if we have enough time left, we will turn this outline into a one-page adventure. We'll create a short summary of everything we have brainstormed, which we can use to run the adventure for our players.

We will aim for a 2-3 hour session, about 1 hour for each step of the process.

# lfg invite 2
[Online][Other] Looking for 2-3 friendly and creative people who want to brainstorm a one-shot adventure together. We'll meet in the voice chat and try to create a story that we can later run for our players. We start 1 hour from now, at 3PM PST.

Hi! I'm looking for 2-3 people who want to brainstorm some story ideas and create an adventure together. We'll meet in the discord voice chat, and try to improvise a one-shot adventure in 2-3 hours. It's really fun to bounce ideas off of other people, stretch your creative muscles, and if we're successful - we'll end up making a story we can run for our players.

We’ll try to make a short, lighthearted, low-combat, system-agnostic adventure set in a fantasy world, a story that anyone can drop into their campaign as a quest, or run as a one-shot.

We'll use the [brainstorming template](https://docs.google.com/document/d/1S0KMVB6qyc_MKvXt2SS4-Zn5seT31QfXjYD1Gb9htzM/) to guide us through the adventure creation process. We'll go through it step by step, and fill it with our ideas. 

We'll brainstorm ideas and establish the key elements of our adventure (interesting premise, the goal our players will pursue, setting and locations they'll visit, NPCs they'll meet, challenges they'll encounter). 

Then, we'll try to to combine these ideas into a short outline of an adventure, put it all together into a list of scenes that add up to an interesting story that makes sense. It will be a short summary of everything we have brainstormed, which gives us all the information we need to run the adventure for our players.

You don't need to have any experience with creating adventures, you're welcome to join even if you've never GMd before - don't worry, you'll get a hang of it really quickly, this is a great way to learn and try to create your first adventure.

If I find enough people who want to participate, we'll start 1 hour from now (at 3PM PST).

If that sounds interesting - send me a message, I'm `lumen#7925` on discord.
* Discord invite
**Looking for 3-4 friendly and creative Game Masters who want to brainstorm a one-shot adventure together. We'll meet in the voice chat and try to create a story that we can later run for our players.**
**DM:** @lumen#7925 
**Length of game:** We'll aim for 2 hours, but can be as long as 3.
**Date & Time:** 
4 hours from now, if I manage to find enough people.
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Adventure+Brainstorming&iso=20210523T16&p1=3903
**Spots Taken:** 0/4

**Description:**
Hi! I'm looking for 3-4 people who want to brainstorm some story ideas and create an adventure together. We'll meet in the discord voice chat, and try to improvise a one-shot adventure in 2-3 hours. It's really fun to bounce ideas off of other people, stretch your creative muscles, and if we're successful - we'll end up making a story we can run for our players.

**Requirements:** 
- Some GMing experience will be helpful, but is not required. You're welcome to join even if you've never GMd before, as long as you enjoy storytelling and want to learn how to create adventures.
- Before we start our session, please get familiar with the brainstorming process: https://rpgadventures.io/brainstorming-process

* 10 minutes before the session
# [@-mention people who signed up]
We begin in 10 minutes.

# If not enough people:
@everyone, we begin brainstorming in 10 minutes. We a couple of spots open, if you want - come join us!

This is the google doc we’ll be filling in with ideas, open it before we begin:
[link to the copy of the brainstorming template]
In the google doc go to Tools > Preferences, and uncheck “Automatically Detect Lists”, otherwise google docs autoformatting will be really annoying.

If you haven’t read the guidelines yet - please check them out:
https://rpgadventures.io/brainstorming-guidelines

I also recommend to open a note-taking app, can be convenient. And you can open the writing prompts generator (https://rpgadventures.io/prompts), if you feel like it’ll be useful to you.

* /r/lfg actual play
[Online][Other] Looking for 2-3 friendly people who like improvisation and freeform roleplay, and want to participate in a lighthearted one-shot adventure on our Actual Play youtube channel. We start in 4 hours (10PM BST).

Hey, everyone! Who wants to participate in an actual play one-shot for my youtube channel? 

I'm just getting started, it is a very small, low-production-value, low-expectations experiment. I just think it would be fun to upload the games I'm running to youtube - so we wouldn't just be playing, but also creating something neat we can share with people. You can see one of our previous games [here](https://www.youtube.com/watch?v=Cn9vV_wHpY4).

We will play a lighthearted one-shot focused on storytelling/improvisation/roleplay. We'll be aiming for a 2-3 hour session. 

We will play over the discord video chat (so you do need a webcam to participate), roll the dice in the discord text chat, and after the game I'll upload the video to youtube.

The system we'll be using to play is called Mirage -  it is a roleplaying/storytelling/improv focused game, a very simple and minimalistic set of rules for basicaly freeform roleplay. You can learn the rules and create your character in under 15 minutes.
 
Novice players are welcome! We'll start simple, and get better as we go along. I'm hoping to find some friendly people who are interested in learning and growing together. If you want to experiment with this sort of thing, learn how it's done, and can be patient if things go wrong - you're welcome to join the game!

If that sounds like fun - [learn how to play](https://rpgadventures.io/mirage), create your character, and send me a message! I'm `lumen#7925` on Discord.

* discord actual play
**Looking for 2-3 friendly people who like improvisation and freeform roleplay, and want to participate in a lighthearted one-shot adventure on my Actual Play youtube channel. We start in 4 hours (2PM BST).**

**Platform:** Discord Video Chat.  
**Time:** We start in 4 hours (2pm BST), we'll be aiming for a 2-3 hour session. 
**Players:** Looking for 2-3 players.
**Format:** Lighthearted improvised one-shot.   

Hey, everyone! Who wants to participate in an actual play one-shot for my youtube channel? 

I'm just getting started, it is a very small, low-production-value, low-expectations experiment. I just think it would be fun to upload the games I'm running to youtube - so we wouldn't just be playing, but also creating something neat we can share with people. You can see one of our previous games here:
https://www.youtube.com/watch?v=Cn9vV_wHpY4

We will play a lighthearted one-shot focused on storytelling/improvisation/roleplay. We'll be aiming for a 2-3 hour session. 

We will play over the discord video chat (so you do need a webcam to participate), roll the dice in the discord text chat, and after the game I'll upload the video to youtube.

The system we'll be using to play is called Mirage -  it is a roleplaying/storytelling/improv focused game, a very simple and minimalistic set of rules for basicaly freeform roleplay. You can learn the rules and create your character in under 15 minutes.
 
Novice players are welcome! We'll start simple, and get better as we go along. I'm hoping to find some friendly people who are interested in learning and growing together. If you want to experiment with this sort of thing, learn how it's done, and can be patient if things go wrong - you're welcome to join the game!

If that sounds like fun send me a message, learn how to play (https://rpgadventures.io/mirage), and create your character.

