* <2021-05-18 Tue>
Zootopia inspired adventure, land of antropomorphic animals. Or sentient fantasy monsters, outcasts, living in peaceful utopia.
Resque/Raise baby monster.
Steampunk adventure. Frankenstein's monster.
Gremlins attacking a flying vehicle.
Evil Batman - vigilante aristocrat turned evil. Dark Knight Paladin.

Shrunk to a tiny size.
Kidnap evil emperor.
Brain Slugs.
Jim Carrey's Mask.
Rats need to defend their home from adventurers hired to clear out the basement.

- How could I adapt project hail mary? Tiny creatures are eating the sun?
- How could I adapt animorpjs? Bet between two gods... Brain slugs...
- Evil Batman - that'd be a great villain, rich aristocrat vigilante. Zorro.
- Mad science experiment. Doing what?
- Hamilton - kidnap evil emperor? That's ansick goal.
Okay, lets do better, let's do more!
So. Adventure ideas:
- HC Fictional element - shrunk to a tiny size. Frankenstein's monster. Gremlins attacking a flying vehicle. Brain slugs.
- Setting - Zootopia.
- Antagonist - Evil Batman.
- Plot - kidnap evil emperor.

Batman could be active antagonist? Doing evil stuff out of misguided sense of justice?
Batman wants to exterminate evil monsters?

Evil Batman - airships.
neighborhood of mice.

100 out of my 10 million babies.
Cataclysm

Fluffernutter stole one of them?

the great mouse detective

Cat final horcrux.
humans don't know.

m

fluffernatter.
make iti nto his bellatrix.

terrible acronym.
his evilness.

vista of the dark empire.
clock tower.

eyeball aesthetic.

kilonazis.

i lost the appetite.

politics and power structure.


dollar sign hanging off of it.

cocaine addcition.
I love you and im concerned about you. This is an intervention.

Fighting cheffs. Helping mice.

Wolf 359 (podcast)

Lady Gwenlinda
* <2021-05-20 Thu>
Classy turtles.
Ruler struck with a disease. one of the knights has to find something to break the curse. Fetch quest.

pirate base on floating island.

handglider.

helium jelly fish.

Valient.

no reason not to add an element of mystery.
piraty pirates do the pirate things pirately.
Parrots and Pirates

royal navy

atheist paladin
worshiping richard dawkins.

i decline to acquiest to your request

alabama. trailer park pirates.
