* <2021-05-18 Tue>
Zootopia inspired adventure, land of antropomorphic animals. Or sentient fantasy monsters, outcasts, living in peaceful utopia.
Resque/Raise baby monster.
Steampunk adventure. Frankenstein's monster.
Gremlins attacking a flying vehicle.
Evil Batman - vigilante aristocrat turned evil. Dark Knight Paladin.

Shrunk to a tiny size.
Kidnap evil emperor.
Brain Slugs.
Jim Carrey's Mask.
Rats need to defend their home from adventurers hired to clear out the basement.

- How could I adapt project hail mary? Tiny creatures are eating the sun?
- How could I adapt animorpjs? Bet between two gods... Brain slugs...
- Evil Batman - that'd be a great villain, rich aristocrat vigilante. Zorro.
- Mad science experiment. Doing what?
- Hamilton - kidnap evil emperor? That's ansick goal.
Okay, lets do better, let's do more!
So. Adventure ideas:
- HC Fictional element - shrunk to a tiny size. Frankenstein's monster. Gremlins attacking a flying vehicle. Brain slugs.
- Setting - Zootopia.
- Antagonist - Evil Batman.
- Plot - kidnap evil emperor.

Batman could be active antagonist? Doing evil stuff out of misguided sense of justice?
Batman wants to exterminate evil monsters?

Evil Batman - airships.
neighborhood of mice.

100 out of my 10 million babies.
Cataclysm

Fluffernutter stole one of them?

the great mouse detective

Cat final horcrux.
humans don't know.

m

fluffernatter.
make iti nto his bellatrix.

terrible acronym.
his evilness.

vista of the dark empire.
clock tower.

eyeball aesthetic.

kilonazis.

i lost the appetite.

politics and power structure.


dollar sign hanging off of it.

cocaine addcition.
I love you and im concerned about you. This is an intervention.

Fighting cheffs. Helping mice.

Wolf 359 (podcast)

Lady Gwenlinda
* <2021-05-20 Thu>
Classy turtles.
Ruler struck with a disease. one of the knights has to find something to break the curse. Fetch quest.

pirate base on floating island.

handglider.

helium jelly fish.

Valient.

no reason not to add an element of mystery.
piraty pirates do the pirate things pirately.
Parrots and Pirates

royal navy

atheist paladin
worshiping richard dawkins.

i decline to acquiest to your request

alabama. trailer park pirates.
* <2021-06-02 Wed>

Hive from resident evil.

3 letter agencies.
kgb -
usa -

dark secret
island colony
mutants
help someone to fight a war, on the run from the law
bodyguard, grue from despicable me.
players fighting on the side of the mutants.

ancient abandoned temple.
ancient evil awakened.
help someone smuggle an item.
object is lost hidden or move.
playboy, evil legolas.
slept with a hag in this temple.
he's captured.
smuggle item into the temple.
knight has been awakening this dark evil.
succubied in.

lovable innocent monster, collateral damage.
cute terrask. pink bow.
sea creature
tarask

pouchers, sell to the emperor.

burp baby

he's like a horse.
put on a collar onto it.

they're good guys, shot them down.



reneissanse

Evil Leonardo da Vinci / Tesla / Edison.

Populated area, big city.

Gaining stars in gta.

government official.
mad scientist.

power source out of him.
all the campaign donations I could make to your cause.

3 eyed mermaid from simpsons.
sad mermaid.

fantasy creatures in manattan.

knock over statue of liberty.
border control.

 Cargo ship loses control?
Aliens knock it over on their way out?

davinci wings powered by tesla coil, electric jetpacks.

my guards attack.

hagrid sized toddler.

soldier 2319

soldier - nice
soldier 420 - flamethrower

sucks up to it's side as a barnicle

fantasy new york.

Classy political party.


scooby doo.

while he's being milked.

wanted to prevent immigrants.

proposal in marriage ceremonies.

discuss it with a person, discuss it with the family.
people who want to keep the last name discuss the marriage price.
showing that they can support suppoprt.
set a date for money buy
host a party/dinner.
proof to show that I can take care of home.
i promise to provide, I promise to take care.

bdsm jokes


out of steam
* <2021-06-08 Tue>

When you're scaring nazis you might want to rethink some stuff about your life.

Demonic mushrooms.
Spore fungus.

Infection.
Last of us.
Hive mind.

Out of control spell causes problems.
Toy story.
out of control spell.
voodoo

suits of armor come alive.
frankenstein's monster.

state marshals.

Someone activates magic.

I'm trying to make sure I don't take

Vanessa Helsing

Drinking your brain through a straw through your ear.

okay they won't figure it out, that's on me.
finding the person who's aggroing monsters.
to prove that monsters are always monsters.
copy zootopia. you follow the clues.

monster meth.
unleash it at prom.

does this human skin make me look fat?

you're nerds and you cant even get in

hot topic goths.
Find the drug dealer (Witch Walterine White) inside and force them to help you make the antidote.

clam juice
how do you juice a clam, it's an animal.

mean growls

teenwolf
* <2021-06-14 Mon>
black market
transformed into the ghoul
someone on the run from the law
do it while protecting someone

get pyramid involved.

ghoulish affair

temple of doom

and his loyal warriors

legend of a pyramid and a fountain of youth.

hot on the trail

Bomoh

need a more fun specifics, what kidn of potion, and what kind of fountain?

I love how it's tied in. You go there to find the lost fountain, and that's what's causing the trouble all along.

Mundungu sold the potions by claiming that they grant unparalleled vitality and [fighting powers].

how does the shaman fit in? Does he know where the potions came from?
do we need the spirit summoning? He's the one who's peddling the potions.Can he just

third p word.
potion peddler.
bad potion peddler
creepy potion peddler.
Powerful priceless
pallid pathetic
petty
profane
paranormal
Perilous
