* <2021-02-16 Tue> Animals Kidnap Princesses

Quick introductions, everyone says a bit about themselves.

Spunge and a wet noodle to do it.

im still banned from the northern hemisphere.

dad

bad boy boyfriend to get back at daddy.

celebrate sir reginalds passing.


orso eats food, eats fish based snack.

alice in wonderland

start creating tableware from crystals

Tiny right hand advisor.
tiny man. with large glasses.
Land of the oasis.
father of children
lord sisymum.

Climax?
rainbow being formed as it passes through the hair.

10 points to gryffindor.

we love each other like greek brothers.
trailer park in alabama.


marry the princess,

you can just do it

gnarly



thanos

torchlights

telepathic spiders

and have a wedding

propose.

combine it with

drop dead delicious

im damn near sober, this sucks

plays quidditch on the weekends

surfboard the blade

my favor is that I ask for 1000 favors.

it always turns out to be sentient.

not worthy fo the sultan

canadilina

literally party animals

chvorka

george washingtron judge wig

* <2021-02-21 Sun> Escape from the dark lord's ship


Imprisoned on the ship.
Survive the person who's hunting us down.

prisoners of evil overlord.

sky dragon monster
Air kraken

Job situation.

meg man - goblin
Amanda - elise. helped with armor repairs. kaylee from firefly.
brown hair and pig tails.

there's an armory with all our stuff.

Charky - cat person.


Orc guards.

Careful not to interrupt.

Fancy elves.
Roguish criminals.

make sure not to interrupt and ask people if they wanted to speak up.
just say that when

3 classes of orc kindergarden.

they took all our stuff.

he's one eyed, he can't really wink.

you're pretty smart for a mortal.

elfs - turn things around.

you can definitely do it.

i would roll my eeys if I had any eyes.

grappling hook
smoke poitons.

come with me if you want to live



thext challenge?x

sneak between people.
he knows magic.

crawl on the outside of the

how do you attack the captain

turns into a puddle of goo.

steer the wheel
steer the people off the ship.

