* Seven Samurai
https://storysynth.org/Shuffled/1FIWw_lyefEPF9dc-4C-cBwr9gg3D1QH5vkW89WxGu68/many-onion-used/
– The Heroes
– The Preparations
– The Battle
– The Aftermath

MIB agent?
Lightsaber jedi?
Super honorable?
Rick?
Goofy robot?
Honorable robot?
I wanna be a robot.
I was made

The community of Ikara is frequently harassed by bandits, who threaten violence unless Ikara hands over its scarce resources.

Anicent race.

I'm an invention of a mad scientist!!
I'm often broken.

Quazar
X13

the untested - tinkerer

Centaur scorpion.
Aximilli.

Tagalong fanboy

Esplin

The Veteran
You are a jaded veteran who has seen too much combat.

I'm just an ancient battle droid.
Like that guy from overwatch!
Who's just tired of fighting and he's actually super friendly.

So the scientists just...
Heey, they discovered me guarding the library!
So I got a little rusty.

my code of honor is actual restrictions they have put into my programming.

Centaur scorpion.
And I have a lightsaber.

Archive is deep underground.
Only one way to get in. Through this tunnel.
Hive from resident evil.

Burned woods, countryside.

Maybe this stuff is super valuable and many alien races are fighting over it.

Teaching scientists.
We know bandits origins.
Recent volcanic activity.


# Prepare Ikara for the bandit attack


