* <2021-02-16 Tue> Animals Kidnap Princesses

Quick introductions, everyone says a bit about themselves.

Spunge and a wet noodle to do it.

im still banned from the northern hemisphere.

dad

bad boy boyfriend to get back at daddy.

celebrate sir reginalds passing.


orso eats food, eats fish based snack.

alice in wonderland

start creating tableware from crystals

Tiny right hand advisor.
tiny man. with large glasses.
Land of the oasis.
father of children
lord sisymum.

Climax?
rainbow being formed as it passes through the hair.

10 points to gryffindor.

we love each other like greek brothers.
trailer park in alabama.


marry the princess,

you can just do it

gnarly



thanos

torchlights

telepathic spiders

and have a wedding

propose.

combine it with

drop dead delicious

im damn near sober, this sucks

plays quidditch on the weekends

surfboard the blade

my favor is that I ask for 1000 favors.

it always turns out to be sentient.

not worthy fo the sultan

canadilina

literally party animals

chvorka

george washingtron judge wig

* <2021-02-21 Sun> Escape from the dark lord's ship


Imprisoned on the ship.
Survive the person who's hunting us down.

prisoners of evil overlord.

sky dragon monster
Air kraken

Job situation.

meg man - goblin
Amanda - elise. helped with armor repairs. kaylee from firefly.
brown hair and pig tails.

there's an armory with all our stuff.

Charky - cat person.


Orc guards.

Careful not to interrupt.

Fancy elves.
Roguish criminals.

make sure not to interrupt and ask people if they wanted to speak up.
just say that when

3 classes of orc kindergarden.

they took all our stuff.

he's one eyed, he can't really wink.

you're pretty smart for a mortal.

elfs - turn things around.

you can definitely do it.

i would roll my eeys if I had any eyes.

grappling hook
smoke poitons.

come with me if you want to live



thext challenge?x

sneak between people.
he knows magic.

crawl on the outside of the

how do you attack the captain

turns into a puddle of goo.

steer the wheel
steer the people off the ship.

* <2021-02-22 Mon>

* <2021-02-23 Tue>

salazar description

6 red glowing eyes.
describe how you attack, and what happens to it.
quiet player - what are you up to?

these scars of a warrior not a mathematician

bush that has one too many eyeballs
cactus that has too many teeth

I take some self esteem damage

tiny flower blooms where the water splashed

im still muttering under my breath "not a person, you're not a person, that's what I should've said".

that's for anyone who can understand dog

I speak zombieneese.

Ask maeloki to run the sessions whenever he wants.

red alert

put together some rat poison to get better

emotional support demon right about now.
scratch from inside my head.
that's where my amygdula used to be

it should be abandoned
smoke coming from the center of the camp
throw his finger there.

help you get more zombies to build the city of the undead.


did you guys enjoy it?

tickle the snakes throat.

plan be suppository

get faust to

summarize these adventures, and share them, and grow the community.

More experienced players should probably close it.
But she's nailing it.

for the last time im not gonna deal with the cooky alchemist with the bee problem.
2 days away from retirement.


* <2021-03-02 Tue>
Volcano messing with evil tribe.
Cavemen language.

good guys are mammoth people.
bad guys are dinosaur people.
shamana's mask

Carn Dent.
Pulled away after killing one of the targets.

carn describe how you defeat the dinosaur
charky describe how you defeat the dinosaur


OHMYGOD OHMYGOD OHMYGOD.
TOO ADORABLE.


pizza with dinosaur toppings.

dense forest ahead.

he's been in one, he's seen a tree before

buy a fellow a dinner first.


create an illusion.

endearing I can be.

shaman turns into a gigantic king kong monster

is that something you might be interested in.

riders tell them to lead us

contribute more, try, take responsibility.

making him regret

see you on a flipflop.

summarize the adventures and help to find more players.

something that gives you aids if it bites you.

thursday

Thursday 21:00
