* <2021-02-16 Tue> Animals Kidnap Princesses

Quick introductions, everyone says a bit about themselves.

Spunge and a wet noodle to do it.

im still banned from the northern hemisphere.

dad

bad boy boyfriend to get back at daddy.

celebrate sir reginalds passing.


orso eats food, eats fish based snack.

alice in wonderland

start creating tableware from crystals

Tiny right hand advisor.
tiny man. with large glasses.
Land of the oasis.
father of children
lord sisymum.

Climax?
rainbow being formed as it passes through the hair.

10 points to gryffindor.

we love each other like greek brothers.
trailer park in alabama.


marry the princess,

you can just do it

gnarly



thanos

torchlights

telepathic spiders

and have a wedding

propose.

combine it with

drop dead delicious

im damn near sober, this sucks

plays quidditch on the weekends

surfboard the blade

my favor is that I ask for 1000 favors.

it always turns out to be sentient.

not worthy fo the sultan

canadilina

literally party animals

chvorka

george washingtron judge wig

* <2021-02-21 Sun> Escape from the dark lord's ship


Imprisoned on the ship.
Survive the person who's hunting us down.

prisoners of evil overlord.

sky dragon monster
Air kraken

Job situation.

meg man - goblin
Amanda - elise. helped with armor repairs. kaylee from firefly.
brown hair and pig tails.

there's an armory with all our stuff.

Charky - cat person.


Orc guards.

Careful not to interrupt.

Fancy elves.
Roguish criminals.

make sure not to interrupt and ask people if they wanted to speak up.
just say that when

3 classes of orc kindergarden.

they took all our stuff.

he's one eyed, he can't really wink.

you're pretty smart for a mortal.

elfs - turn things around.

you can definitely do it.

i would roll my eeys if I had any eyes.

grappling hook
smoke poitons.

come with me if you want to live



thext challenge?x

sneak between people.
he knows magic.

crawl on the outside of the

how do you attack the captain

turns into a puddle of goo.

steer the wheel
steer the people off the ship.

* <2021-02-22 Mon>

* <2021-02-23 Tue>

salazar description

6 red glowing eyes.
describe how you attack, and what happens to it.
quiet player - what are you up to?

these scars of a warrior not a mathematician

bush that has one too many eyeballs
cactus that has too many teeth

I take some self esteem damage

tiny flower blooms where the water splashed

im still muttering under my breath "not a person, you're not a person, that's what I should've said".

that's for anyone who can understand dog

I speak zombieneese.

Ask maeloki to run the sessions whenever he wants.

red alert

put together some rat poison to get better

emotional support demon right about now.
scratch from inside my head.
that's where my amygdula used to be

it should be abandoned
smoke coming from the center of the camp
throw his finger there.

help you get more zombies to build the city of the undead.


did you guys enjoy it?

tickle the snakes throat.

plan be suppository

get faust to

summarize these adventures, and share them, and grow the community.

More experienced players should probably close it.
But she's nailing it.

for the last time im not gonna deal with the cooky alchemist with the bee problem.
2 days away from retirement.


* <2021-03-02 Tue>
Volcano messing with evil tribe.
Cavemen language.

good guys are mammoth people.
bad guys are dinosaur people.
shamana's mask

Carn Dent.
Pulled away after killing one of the targets.

carn describe how you defeat the dinosaur
charky describe how you defeat the dinosaur


OHMYGOD OHMYGOD OHMYGOD.
TOO ADORABLE.


pizza with dinosaur toppings.

dense forest ahead.

he's been in one, he's seen a tree before

buy a fellow a dinner first.


create an illusion.

endearing I can be.

shaman turns into a gigantic king kong monster

is that something you might be interested in.

riders tell them to lead us

contribute more, try, take responsibility.

making him regret

see you on a flipflop.

summarize the adventures and help to find more players.

something that gives you aids if it bites you.

thursday

Thursday 21:00

* <2021-03-16 Tue> Hogwarts Mirror.
Story games work!


* <2021-03-20 Sat> Fiasco - Dylan and Sheep
No GM. Explanation and tips.
Small time capers went horribly wrong.
Powerful ambition, poor impulse control.
Catastrophy.
That's what we want, there's no winning in this game.
Get cahracter into porblems they can't handle, and see how it falls apart.
Avoid politics in the US.

# Rules
Setup - 1/3rd.
Enter player names.
2 parts. Problems develop, 2nd act - things go off the rails. Epilogue.
Scenes. On your turn, look at some experience your character is having, your character has to be in it.
Someone ends up with a red/black die.
high number in one category your life is good.
if red/black is equal, your life will be real bad.


using prompts to connect characters together.

Main St - small town, late 90s.
boomtown - old west
superhero
last frontier - alasca
hotel - small town in cansas, motel

zorro.

nerdy guy who wants to become the famous criminal to get a girl.

lean on need/relationship by default.

somethign

Kurt

Dylan
Damien Palmer
Wyatt
Luke
Damien
Remy
Sawyer
Humble sheep farmer


pushing hard for a nickname
nobody calls him that

ruthless synonym
Vicious V
Brutal Bob

two competing groups of criminals after the same target.

Dylan is in love with Harriett, and pissed at Mr Henry, Jealous.

1.5 hours for setup.

Follow your character through a scene.
The purpose of scenes is to take a look at something uncertain.
Wanna not quite know how it's going to end.
That's what makes it worth roleplaying.

Set the scene, or resolve it.
Does anyone have a good idea for the scene? Then you're the one who ends it.
If I set the scene, I don't get to choose how it ends.
Does the character get what they wanted?
Scene works out well or badly.

decided by anyone, at any point.

How long scenes are?
Scenes should be short. 3 minutes. Big narrative moves.
Pick who else is in the scene.


pick dice, give it to player. just from the total list of tokens.

# Mr Banks
Loves Harriet, cares about Gobelet.

# Dylan
Humble Sheep Farmer, Fell in love with Harriet. Smart but soft.
He's really sick of this town, pushed around by everyone.
Fell in love with Mr Banks girlfriend.
Brutal Bob. Be my Mentor.
Mr B.
I want the Goblet. My darling Harriet will finally be in love with me.

# Harriet
Her dad doesn't care about her.
Harriet runs a hotel
wants to go out on her own in a big heist.

# Brutal Bob
Baddest man in London.
Going around robbing banks, extortion, racketeering.
Pretends to be as american as possible.

# Darlene
Darlene's baby.
Works at a saloon.
Never had big dreams.
Really does love this town.
Bring down the Banker.
Ended up with a baby. randevou with a tall dark stranger.
Baby means everything to her.
She's got some dirt on mr banks. And wants to use it againt him.
Him using old money. it would ruin his reputation.

# Act 2
When you get red or black, you keep it, you're not giving it away.
** Scenes
# Darlene - Mr Banks
Deadstone Tavern
Closing time, kickback relax, have some drinks, Gold rush, after digging mines, swapping stories.
Hides her displeasure with the smile.
town going to shambles.
Shipment coming to town, a lot riding on it.
Self made man everyone sees me as. he holds it up, he's the pillar.

# Hariett - Mr Banks
Restaurant of the hotel.
Mr Banks comes to check on the safe.
How do you do? I've got the devil in my head this morning.
Beautiful French Boy. Are you just here to tell me about your sins?
Don't everyone find themselves with a drink now and again?
Whatever do you keep in there banks? Perhaps if we were closer.
Big shipment coming in. Details about the shipment.
Kisses her hand wetly.
#jok "
what a novelty, a scene with banks.

# Mr Banks
Banks is at home, got his lantern lit. Baby cryng in another room.
Takes the baby.

# Trying to impress Harriett
sniff her hair
Meet her and mr b.

Darlene is Hairess.
He stealthily kidnapped the baby.
Bankses mansion.

Bringing flowers to harriet?

Mr B, I've got a score for us.
Casing the Joint.


# Greenhouse
waiting
yeah babe, we just kinda wanted to swing by, no big deal.

bushwak him on a particular day.
we need that contract.

yeah, whatver, maybe, through my tears.
i give a bow and shuffle after him.


# Brutal Bob - Darlene
Tells her that he kidnapped a baby.

# Harriett
Harriett - wants to rob train shipment.
She wanted us to help the documents.
brutal will kidnap him.
so that he keeps the documents and the baby in one place.
kidnap him and get contract.
1. Get a baby.
2. Steal the shipment and live like queens.

# Banks sends ransom note
Sending ransom note
force her to marry him


dylan fucks up.
house

Combine the heists?

Brutal Bob knows we're coming?

stupid plan executed to perfection

** Act 2
# Harriet Mr Banks
I gotta marry me
that bastard he tricked her
we need to rescue her.
i've had a horrible dream
it's just the liver.

answered the question of the scene.

What are you trying to do in the present?
So they're trying to get to the train.
Stick the hankerchief into my liver hole.

give me back my darling, let her go.

im not leaving without my treasure.
letter says where the shipment is.

Stand off between Harriet and Bob!
And I have to choose.

I dive in front of the bullet.

shipment
not the deed but the actual animals.

special sheep connection to save harriett.

you see the two graves
Ruthless D
Brutal Bob

2black - 4red = 2red

staring at the hancerchief which is all that's left of his love.

let the big crime spree.


after credit scene.

* Fiasco 2 - Frost
Andy, IT consultant, Cleopatra.
Coding.
C[eye]an
Eelde

Ice - murder at antarctic station.
Zoo - shaky finances in zoo.
Rocking Band - showbiz.
Transatlantic - 19hundreds. Cruiseship. 
Theater production.
Object zero. submarine. secret mission. creature on the outside.

transatlantic
https://drive.google.com/file/d/1vukZloIc1IK7IQ782hxBf6v3-3HOa87s/view

rockstar.


Justin Bieber gone Goth.
Vain and horrible.
Manager screwed me. Just moved on to the next hot thing.

Ace Cooper
Lars Amos
Syd 

And now I owe you.

Lars
Teenage pop star.
My manger has replaced me with the next hot thing.
So I gone dark and got into rock. Trying to make it as a rock artist.
Getting by as an Instagram Influencer.
Thats whats up thats whats up.

Ask Nathan to make up for it. Finally, you can repay a favor.

Help me to get revenge

If it goes well, my career will be made.

You convince Harvey to
Sabotage the concert.
Before the concert. We need to sabotage her.
replace him.
convince me to participate in it
battle of the bands.

defeat this band

surrounded by fans
went to a hardcore rock club, and they really arent' digging my vibes.

Rebecca Ruben

2 blue.


dangerous animal gets loose.

take one of us hostage

2 red

snorting his ashes.


