* Seven Samurai
https://storysynth.org/Shuffled/1FIWw_lyefEPF9dc-4C-cBwr9gg3D1QH5vkW89WxGu68/many-onion-used/
– The Heroes
– The Preparations
– The Battle
– The Aftermath

MIB agent?
Lightsaber jedi?
Super honorable?
Rick?
Goofy robot?
Honorable robot?
I wanna be a robot.
I was made

The community of Ikara is frequently harassed by bandits, who threaten violence unless Ikara hands over its scarce resources.

Anicent race.

I'm an invention of a mad scientist!!
I'm often broken.

Quazar
X13

the untested - tinkerer

Centaur scorpion.
Aximilli.

Tagalong fanboy

Esplin

The Veteran
You are a jaded veteran who has seen too much combat.

I'm just an ancient battle droid.
Like that guy from overwatch!
Who's just tired of fighting and he's actually super friendly.

So the scientists just...
Heey, they discovered me guarding the library!
So I got a little rusty.

my code of honor is actual restrictions they have put into my programming.

Centaur scorpion.
And I have a lightsaber.

Archive is deep underground.
Only one way to get in. Through this tunnel.
Hive from resident evil.

Burned woods, countryside.

Maybe this stuff is super valuable and many alien races are fighting over it.

Teaching scientists.
We know bandits origins.
Recent volcanic activity.


# Prepare Ikara for the bandit attack


* <2021-03-04 Thu>
Ask for contact info.
Do you have a way of rolling the dice?

cunning can just be my own thing.

rad pirate

constantly on the verge of mutiny
a lot of drama

two ton - gunner.

fallen out of favor.

dreadnaught.
Port Royal
civilized
loot

captain sourcheese

jack fletcher

this is not the last we have of this conversation
and I storm off.

just in a rowboat


run away with me elizabeth, i know we just met, but I can not live without you anymore.

every second theres a pause in a conversation i get back to making out with elizabeth

i couldnt help but notice

players have ownership
2 objectives at the same time
need to know the situation and the goal

set up your destiny,

face your destiny

microscope
quiet year
