* <2020-09-05 Sat>
sd
lo-fi-loki
bdadkins

sell magical creatures on a black market

threat from the mafia, we're coming for you

massive inflation
steal as much gold as possible for good

artifact teleports the gold to the bank.

gold mimic, eats other gold coins
plant gold mimics around town

goblins/kobolds

everything turns to gold

philosopher's stone / mitus touch.

most of the gold is fake.

alchemist as an antagonist


gold summons dragons

competing dragons

scrudge mc duck
someone stockpiled it

gigantic mimic fighting a dragon

heavy handed metaphor

crater of the doramn volcanoe

minors, forge
city on the rim

a bunch of bridges

insinuation
* <2020-09-14 Mon>
Animals

Aha, blank sheet doesn't have id huh.

that's weird, when i delete sheet it just calls create sheet.
why wouldnt it make an id.

prison break situation

epic journey


track the rest of their heard through a terrain.

disney princess him, he has animal friends

stages
3 stages
- selecting the date, finding ladies
- multiple dates, getting the first date to go right.
  this this and that didn't work.
- something happens out of their control.

external stakes

he's rich, his parents cut him off financially
has to find someone, or he won't inherit the forutne.

sibling shitty
zapp brannigan
bard is like michael cera

king died, you need a queen to be coronated.

animals involved in political intrigue

family airloom that's powerful.

proposal so she says yes.

50 first dates, 40 year old virgin.

strict parents

brother is antagonist

strict conservative father
get serious
you're not a man until you get married.


they own the adventurer's guild
otherwise they won't get contracts


city urban

german

getting mindflayer laid

pirate

satyrs
logical nerdy dwarf

then there's a reason to reproduce

brother trying to prevent the proposal.


father would immediately know it's their fault

find out

suitors come back forr evenge

brotehr has to be amrried?


everyone has already rejected him?
super specific

figure out reasons why not.

makeover montage

send someone else

everything that has happened everythign is on fire
swarms of mosquitos
that's biblical

sun is like moon during the day


what a nightmare

robert evans

border patrol has authority that extend 100 miles from every airport

when sky turns red abovey our head
machenist programmer alcohol

vodka that teleports you forward in time

build airplanes.
applying to space x.
gun smiths
can build anything
giant blocks of titanium and see them catch fires
play with robots
* <2020-09-16 Wed>

snake killed a child, and now they're

water is gone
find old weapons

rango

travel down the river

village set up by the despot fox, controls the water
mad max

slagger the cruel
fox with burnt face

mountain taken over by hoard
pull resources together to protect the ancestral home.

siege, r

snake
bear
muck

preindustrial revolution

helping towns along the way.

amerian south

burned up forest

American Southwest

surfin the wave.

lady tied to the railroad track

kaylee from firefly

penguins from madagascar take over human b

hide information, change goal


Afternoon
* <2020-09-17 Thu>

Fabricate small animals.

Ring can only be used by the true hero,
they're the heroes.

guardians of the galaxy.

locate good dragon.

heroes want to kill a dragon
dragon keeps the order

who wants to read a movie

stationary
can only act through cnotrolling the animals

octopus
owl


villain in the human city

country hired people to defeat the adventures.
good people are antagonist.
kill the dragon, good players trying to kill a good dragon.



tiger pursues them.

slow down the familiar.

ring gets stolen.

magicpunk sky islands detective nuar.

harry potter jumping between adventures.

cinderclaws delivering ash to bad people



charming and debonair

vinny the vampire, hawaian shirts, hammock coffin.

hilbilly elves that sniff coconut moonshine, and ride giant amphibious iguanas.
attacked by the giant crabs.

fate

60 second rule.

4 stone tabl on
yoth - strength
myril - grace - foutain
croth - treachury - knife swing
alfred - beginnings - long road/ladder
make a symbol with your body, first letter

