* <2020-09-05 Sat>
sd
lo-fi-loki
bdadkins

sell magical creatures on a black market

threat from the mafia, we're coming for you

massive inflation
steal as much gold as possible for good

artifact teleports the gold to the bank.

gold mimic, eats other gold coins
plant gold mimics around town

goblins/kobolds

everything turns to gold

philosopher's stone / mitus touch.

most of the gold is fake.

alchemist as an antagonist


gold summons dragons

competing dragons

scrudge mc duck
someone stockpiled it

gigantic mimic fighting a dragon

heavy handed metaphor

crater of the doramn volcanoe

minors, forge
city on the rim

a bunch of bridges

insinuation
* <2020-09-14 Mon>
Animals

Aha, blank sheet doesn't have id huh.

that's weird, when i delete sheet it just calls create sheet.
why wouldnt it make an id.

prison break situation

epic journey


track the rest of their heard through a terrain.

disney princess him, he has animal friends

stages
3 stages
- selecting the date, finding ladies
- multiple dates, getting the first date to go right.
  this this and that didn't work.
- something happens out of their control.

external stakes

he's rich, his parents cut him off financially
has to find someone, or he won't inherit the forutne.

sibling shitty
zapp brannigan
bard is like michael cera

king died, you need a queen to be coronated.

animals involved in political intrigue

family airloom that's powerful.

proposal so she says yes.

50 first dates, 40 year old virgin.

strict parents

brother is antagonist

strict conservative father
get serious
you're not a man until you get married.


they own the adventurer's guild
otherwise they won't get contracts


city urban

german

getting mindflayer laid

pirate

satyrs
logical nerdy dwarf

then there's a reason to reproduce

brother trying to prevent the proposal.


father would immediately know it's their fault

find out

suitors come back forr evenge

brotehr has to be amrried?


everyone has already rejected him?
super specific

figure out reasons why not.

makeover montage

send someone else

everything that has happened everythign is on fire
swarms of mosquitos
that's biblical

sun is like moon during the day


what a nightmare

robert evans

border patrol has authority that extend 100 miles from every airport

when sky turns red abovey our head
machenist programmer alcohol

vodka that teleports you forward in time

build airplanes.
applying to space x.
gun smiths
can build anything
giant blocks of titanium and see them catch fires
play with robots
* <2020-09-16 Wed>

snake killed a child, and now they're

water is gone
find old weapons

rango

travel down the river

village set up by the despot fox, controls the water
mad max

slagger the cruel
fox with burnt face

mountain taken over by hoard
pull resources together to protect the ancestral home.

siege, r

snake
bear
muck

preindustrial revolution

helping towns along the way.

amerian south

burned up forest

American Southwest

surfin the wave.

lady tied to the railroad track

kaylee from firefly

penguins from madagascar take over human b

hide information, change goal


Afternoon
* <2020-09-17 Thu>

Fabricate small animals.

Ring can only be used by the true hero,
they're the heroes.

guardians of the galaxy.

locate good dragon.

heroes want to kill a dragon
dragon keeps the order

who wants to read a movie

stationary
can only act through cnotrolling the animals

octopus
owl


villain in the human city

country hired people to defeat the adventures.
good people are antagonist.
kill the dragon, good players trying to kill a good dragon.



tiger pursues them.

slow down the familiar.

ring gets stolen.

magicpunk sky islands detective nuar.

harry potter jumping between adventures.

cinderclaws delivering ash to bad people



charming and debonair

vinny the vampire, hawaian shirts, hammock coffin.

hilbilly elves that sniff coconut moonshine, and ride giant amphibious iguanas.
attacked by the giant crabs.

fate

60 second rule.

4 stone tabl on
yoth - strength
myril - grace - foutain
croth - treachury - knife swing
alfred - beginnings - long road/ladder
make a symbol with your body, first letter
* <2021-01-14 Thu> New Start

Johnny.

Nadav, GM, gming for a couple of years. Works in DnD.
3 months course in storytelling.

Education, studying to be a teacher. Creative work.

Sanar. Brainstorming.

high fantasy area, anthrax+worldworldz.
expand zones where virus can't reach.

bigger more aggressive snails

futurama

super powerful but also slow and not very smart.
assault weapnos - salt weapon.
witty sanil. salty comments.

Sentient walking tower.
City built on top of a snail.
Used to be mages tower.
Used to be Mage's tower.
freaky friday with the tower.

lighthouse luring people in.

Tyrannical. Heisting from an elf king.


let players do what they want.

creepy doll house.



Villain specializing in shrink magic.
varyign degrees of shrinkage especially when it's cold.

Wake up in the city

Honey I shrunk the Mage


Magic Forest.
On the side of the forest.
Result of the magical experiment.

toxic fumens.

dystopian bee society, dont worry be happy, where nobody can be
don't worry be happy
let it be

save her uncle mage
He wants to stay with the bees.

b wants the d.

best way to enjoy honey

controlling girlfriend.

for the sake of the hive, machiavellian politician.

too afraid to break up with her?
she's in love with him.

while she's in the shower

He was making a love potion.




* <2021-01-16 Sat>

teenage werewolf - hunt her down without harming her
broker peace between giants
sinister cult, sacrifices
players being superheroes
Romeo and Juliet. Two warring families.
Vampire spy.
Monster's inc. Children, monsters in the closet.
Child tyrant. Creepy child sees the fantasy world in his dreams.
Train/Zeppelin adventure. "Speed".
Deal with the Devil.
Something gains sentience. Objects come to life.
Return a baby monster to it's parents.
Love Potion in water supply.
Don't go below the speed limit - if you stop moving a person dies or a bomb explodes (Speed, Crank, The X-Files "Drive" episode).
Inanimate objects come to life.
The evil adventuring party. Superhero turned evil.
People become posessed.
Mummy lord comes back to life.
Perform a play/wedding/dinner that must go without a hitch.

hunt down sasquatch
get there, get it out of there.
griffon

orcs really like unicorn meat.

Trade dispute between kingdom and orcs.
Negotiation


leviathan, pirate island

god of trickery trapped you inside the pocket dimension.

theme, non-euclidian, mc escher,

don't interrupt

Animated things, cursed by mage.
Uncurse them.
Break the curse.

fork - please dont kill me I have a family.

sell a bunch of wedding rings.
minor god wants to increase the tribute.

combine them?


they die before the adventure begins.
prevent town from being slaughtered.
defeat him,
they're not aware they're undead.
brothers help me.


>> Give adventure a title.
- How can we combine two ideas?
- Better way of picking ideas.


lead zombie rebellion.
convince people to not freak out.


Hire to sabotage.
Set them up.


Orc princess ran away with human guy.

King thinks orcs kidnapped the princess, but in reality they ran away.
Or maybe they have to find the princess.
Find the princess that's ran away.

Hunt the piece animal.

orcs compete with the party to capture the thing.

orcs, humans

we're sent by prince and princess.

Couple is tested to find the unicorn thing.
If they capture the unicorn.
orcs try to prevent you from succeeding,
humans try to help.

justify invasion.

capturing unicorn helps them to runaway?
Asking to cheat.


so something to prove their love and prevent a war.

they ran away to capture the beast

Monster cemetery
Mintorur cave

lavafalls

Swamp Witch

flip of the orc brothers.

previous adventureres captured it

feel free to run your own sessions.

Tuco from breaking bad


suitor was stolen.

king let the paladins know that the party

- beat up weak orcs, introduce brothers
-
- 
