* <2021-02-16 Tue> First adventure

Quick introductions, everyone says a bit about themselves.

Spunge and a wet noodle to do it.

im still banned from the northern hemisphere.

dad

bad boy boyfriend to get back at daddy.

celebrate sir reginalds passing.


orso eats food, eats fish based snack.

alice in wonderland

start creating tableware from crystals

Tiny right hand advisor.
tiny man. with large glasses.
Land of the oasis.
father of children
lord sisymum.

Climax?
rainbow being formed as it passes through the hair.

10 points to gryffindor.

we love each other like greek brothers.
trailer park in alabama.


marry the princess,

you can just do it

gnarly



thanos

torchlights

telepathic spiders

and have a wedding

propose.

combine it with

drop dead delicious

im damn near sober, this sucks

plays quidditch on the weekends

surfboard the blade

my favor is that I ask for 1000 favors.

it always turns out to be sentient.

not worthy fo the sultan

canadilina

literally party animals

chvorka

george washingtron judge wig

